// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UserInf struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	NikeName             string   `protobuf:"bytes,2,opt,name=nike_name,json=nikeName,proto3" json:"nike_name,omitempty"`
	UserName             string   `protobuf:"bytes,3,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	UserStats            uint64   `protobuf:"varint,5,opt,name=user_stats,json=userStats,proto3" json:"user_stats,omitempty"`
	IdentityCardType     uint64   `protobuf:"varint,6,opt,name=identity_card_type,json=identityCardType,proto3" json:"identity_card_type,omitempty"`
	IdentityCardNo       string   `protobuf:"bytes,7,opt,name=identity_card_no,json=identityCardNo,proto3" json:"identity_card_no,omitempty"`
	MobilePhone          string   `protobuf:"bytes,8,opt,name=mobile_phone,json=mobilePhone,proto3" json:"mobile_phone,omitempty"`
	UserEmail            string   `protobuf:"bytes,9,opt,name=user_email,json=userEmail,proto3" json:"user_email,omitempty"`
	Gender               string   `protobuf:"bytes,10,opt,name=gender,proto3" json:"gender,omitempty"`
	UserPoint            uint64   `protobuf:"varint,11,opt,name=user_point,json=userPoint,proto3" json:"user_point,omitempty"`
	RegisterTime         string   `protobuf:"bytes,12,opt,name=register_time,json=registerTime,proto3" json:"register_time,omitempty"`
	ModifiedTime         string   `protobuf:"bytes,14,opt,name=modified_time,json=modifiedTime,proto3" json:"modified_time,omitempty"`
	TranUserName         string   `protobuf:"bytes,15,opt,name=tran_user_name,json=tranUserName,proto3" json:"tran_user_name,omitempty"`
	TranUserAccount      string   `protobuf:"bytes,16,opt,name=tran_user_account,json=tranUserAccount,proto3" json:"tran_user_account,omitempty"`
	TranUserPwd          string   `protobuf:"bytes,17,opt,name=tran_user_pwd,json=tranUserPwd,proto3" json:"tran_user_pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInf) Reset()         { *m = UserInf{} }
func (m *UserInf) String() string { return proto.CompactTextString(m) }
func (*UserInf) ProtoMessage()    {}
func (*UserInf) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *UserInf) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInf.Unmarshal(m, b)
}
func (m *UserInf) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInf.Marshal(b, m, deterministic)
}
func (m *UserInf) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInf.Merge(m, src)
}
func (m *UserInf) XXX_Size() int {
	return xxx_messageInfo_UserInf.Size(m)
}
func (m *UserInf) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInf.DiscardUnknown(m)
}

var xxx_messageInfo_UserInf proto.InternalMessageInfo

func (m *UserInf) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UserInf) GetNikeName() string {
	if m != nil {
		return m.NikeName
	}
	return ""
}

func (m *UserInf) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *UserInf) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserInf) GetUserStats() uint64 {
	if m != nil {
		return m.UserStats
	}
	return 0
}

func (m *UserInf) GetIdentityCardType() uint64 {
	if m != nil {
		return m.IdentityCardType
	}
	return 0
}

func (m *UserInf) GetIdentityCardNo() string {
	if m != nil {
		return m.IdentityCardNo
	}
	return ""
}

func (m *UserInf) GetMobilePhone() string {
	if m != nil {
		return m.MobilePhone
	}
	return ""
}

func (m *UserInf) GetUserEmail() string {
	if m != nil {
		return m.UserEmail
	}
	return ""
}

func (m *UserInf) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *UserInf) GetUserPoint() uint64 {
	if m != nil {
		return m.UserPoint
	}
	return 0
}

func (m *UserInf) GetRegisterTime() string {
	if m != nil {
		return m.RegisterTime
	}
	return ""
}

func (m *UserInf) GetModifiedTime() string {
	if m != nil {
		return m.ModifiedTime
	}
	return ""
}

func (m *UserInf) GetTranUserName() string {
	if m != nil {
		return m.TranUserName
	}
	return ""
}

func (m *UserInf) GetTranUserAccount() string {
	if m != nil {
		return m.TranUserAccount
	}
	return ""
}

func (m *UserInf) GetTranUserPwd() string {
	if m != nil {
		return m.TranUserPwd
	}
	return ""
}

//用户的联系人列表
type Passenger struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PassengerName        string   `protobuf:"bytes,3,opt,name=passenger_name,json=passengerName,proto3" json:"passenger_name,omitempty"`
	SexCode              string   `protobuf:"bytes,4,opt,name=sex_code,json=sexCode,proto3" json:"sex_code,omitempty"`
	SexName              string   `protobuf:"bytes,5,opt,name=sex_name,json=sexName,proto3" json:"sex_name,omitempty"`
	BornDate             string   `protobuf:"bytes,6,opt,name=born_date,json=bornDate,proto3" json:"born_date,omitempty"`
	CountryCode          string   `protobuf:"bytes,7,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	PassengerIdTypeCode  string   `protobuf:"bytes,8,opt,name=passenger_id_type_code,json=passengerIdTypeCode,proto3" json:"passenger_id_type_code,omitempty"`
	PassengerIdTypeName  string   `protobuf:"bytes,9,opt,name=passenger_id_type_name,json=passengerIdTypeName,proto3" json:"passenger_id_type_name,omitempty"`
	PassengerIdNo        string   `protobuf:"bytes,10,opt,name=passenger_id_no,json=passengerIdNo,proto3" json:"passenger_id_no,omitempty"`
	PassengerType        string   `protobuf:"bytes,11,opt,name=passenger_type,json=passengerType,proto3" json:"passenger_type,omitempty"`
	PassengerFlag        string   `protobuf:"bytes,12,opt,name=passenger_flag,json=passengerFlag,proto3" json:"passenger_flag,omitempty"`
	PassengerTypeName    string   `protobuf:"bytes,13,opt,name=passenger_type_name,json=passengerTypeName,proto3" json:"passenger_type_name,omitempty"`
	MobileNo             string   `protobuf:"bytes,14,opt,name=mobile_no,json=mobileNo,proto3" json:"mobile_no,omitempty"`
	PhoneNo              string   `protobuf:"bytes,15,opt,name=phone_no,json=phoneNo,proto3" json:"phone_no,omitempty"`
	Email                string   `protobuf:"bytes,16,opt,name=email,proto3" json:"email,omitempty"`
	Address              string   `protobuf:"bytes,17,opt,name=address,proto3" json:"address,omitempty"`
	Postalcode           string   `protobuf:"bytes,18,opt,name=postalcode,proto3" json:"postalcode,omitempty"`
	FirstLetter          string   `protobuf:"bytes,19,opt,name=first_letter,json=firstLetter,proto3" json:"first_letter,omitempty"`
	RecordCount          string   `protobuf:"bytes,20,opt,name=recordCount,proto3" json:"recordCount,omitempty"`
	TotalTimes           string   `protobuf:"bytes,21,opt,name=total_times,json=totalTimes,proto3" json:"total_times,omitempty"`
	IndexId              string   `protobuf:"bytes,22,opt,name=index_id,json=indexId,proto3" json:"index_id,omitempty"`
	AllEncStr            string   `protobuf:"bytes,23,opt,name=allEncStr,proto3" json:"allEncStr,omitempty"`
	IsAdult              string   `protobuf:"bytes,24,opt,name=isAdult,proto3" json:"isAdult,omitempty"`
	IsYongThan10         string   `protobuf:"bytes,25,opt,name=isYongThan10,proto3" json:"isYongThan10,omitempty"`
	IsYongThan14         string   `protobuf:"bytes,26,opt,name=isYongThan14,proto3" json:"isYongThan14,omitempty"`
	IsOldThan60          string   `protobuf:"bytes,27,opt,name=isOldThan60,proto3" json:"isOldThan60,omitempty"`
	GatBornDate          string   `protobuf:"bytes,28,opt,name=gat_born_date,json=gatBornDate,proto3" json:"gat_born_date,omitempty"`
	GatValidDateStart    string   `protobuf:"bytes,29,opt,name=gat_valid_date_start,json=gatValidDateStart,proto3" json:"gat_valid_date_start,omitempty"`
	GatValidDateEnd      string   `protobuf:"bytes,30,opt,name=gat_valid_date_end,json=gatValidDateEnd,proto3" json:"gat_valid_date_end,omitempty"`
	GatVersion           string   `protobuf:"bytes,31,opt,name=gat_version,json=gatVersion,proto3" json:"gat_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Passenger) Reset()         { *m = Passenger{} }
func (m *Passenger) String() string { return proto.CompactTextString(m) }
func (*Passenger) ProtoMessage()    {}
func (*Passenger) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *Passenger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Passenger.Unmarshal(m, b)
}
func (m *Passenger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Passenger.Marshal(b, m, deterministic)
}
func (m *Passenger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Passenger.Merge(m, src)
}
func (m *Passenger) XXX_Size() int {
	return xxx_messageInfo_Passenger.Size(m)
}
func (m *Passenger) XXX_DiscardUnknown() {
	xxx_messageInfo_Passenger.DiscardUnknown(m)
}

var xxx_messageInfo_Passenger proto.InternalMessageInfo

func (m *Passenger) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Passenger) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Passenger) GetPassengerName() string {
	if m != nil {
		return m.PassengerName
	}
	return ""
}

func (m *Passenger) GetSexCode() string {
	if m != nil {
		return m.SexCode
	}
	return ""
}

func (m *Passenger) GetSexName() string {
	if m != nil {
		return m.SexName
	}
	return ""
}

func (m *Passenger) GetBornDate() string {
	if m != nil {
		return m.BornDate
	}
	return ""
}

func (m *Passenger) GetCountryCode() string {
	if m != nil {
		return m.CountryCode
	}
	return ""
}

func (m *Passenger) GetPassengerIdTypeCode() string {
	if m != nil {
		return m.PassengerIdTypeCode
	}
	return ""
}

func (m *Passenger) GetPassengerIdTypeName() string {
	if m != nil {
		return m.PassengerIdTypeName
	}
	return ""
}

func (m *Passenger) GetPassengerIdNo() string {
	if m != nil {
		return m.PassengerIdNo
	}
	return ""
}

func (m *Passenger) GetPassengerType() string {
	if m != nil {
		return m.PassengerType
	}
	return ""
}

func (m *Passenger) GetPassengerFlag() string {
	if m != nil {
		return m.PassengerFlag
	}
	return ""
}

func (m *Passenger) GetPassengerTypeName() string {
	if m != nil {
		return m.PassengerTypeName
	}
	return ""
}

func (m *Passenger) GetMobileNo() string {
	if m != nil {
		return m.MobileNo
	}
	return ""
}

func (m *Passenger) GetPhoneNo() string {
	if m != nil {
		return m.PhoneNo
	}
	return ""
}

func (m *Passenger) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Passenger) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Passenger) GetPostalcode() string {
	if m != nil {
		return m.Postalcode
	}
	return ""
}

func (m *Passenger) GetFirstLetter() string {
	if m != nil {
		return m.FirstLetter
	}
	return ""
}

func (m *Passenger) GetRecordCount() string {
	if m != nil {
		return m.RecordCount
	}
	return ""
}

func (m *Passenger) GetTotalTimes() string {
	if m != nil {
		return m.TotalTimes
	}
	return ""
}

func (m *Passenger) GetIndexId() string {
	if m != nil {
		return m.IndexId
	}
	return ""
}

func (m *Passenger) GetAllEncStr() string {
	if m != nil {
		return m.AllEncStr
	}
	return ""
}

func (m *Passenger) GetIsAdult() string {
	if m != nil {
		return m.IsAdult
	}
	return ""
}

func (m *Passenger) GetIsYongThan10() string {
	if m != nil {
		return m.IsYongThan10
	}
	return ""
}

func (m *Passenger) GetIsYongThan14() string {
	if m != nil {
		return m.IsYongThan14
	}
	return ""
}

func (m *Passenger) GetIsOldThan60() string {
	if m != nil {
		return m.IsOldThan60
	}
	return ""
}

func (m *Passenger) GetGatBornDate() string {
	if m != nil {
		return m.GatBornDate
	}
	return ""
}

func (m *Passenger) GetGatValidDateStart() string {
	if m != nil {
		return m.GatValidDateStart
	}
	return ""
}

func (m *Passenger) GetGatValidDateEnd() string {
	if m != nil {
		return m.GatValidDateEnd
	}
	return ""
}

func (m *Passenger) GetGatVersion() string {
	if m != nil {
		return m.GatVersion
	}
	return ""
}

type InDoneUserLogin struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	MobilePhone          string   `protobuf:"bytes,3,opt,name=mobile_phone,json=mobilePhone,proto3" json:"mobile_phone,omitempty"`
	VerificationCode     string   `protobuf:"bytes,4,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	LoginType            uint64   `protobuf:"varint,5,opt,name=login_type,json=loginType,proto3" json:"login_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InDoneUserLogin) Reset()         { *m = InDoneUserLogin{} }
func (m *InDoneUserLogin) String() string { return proto.CompactTextString(m) }
func (*InDoneUserLogin) ProtoMessage()    {}
func (*InDoneUserLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *InDoneUserLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InDoneUserLogin.Unmarshal(m, b)
}
func (m *InDoneUserLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InDoneUserLogin.Marshal(b, m, deterministic)
}
func (m *InDoneUserLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InDoneUserLogin.Merge(m, src)
}
func (m *InDoneUserLogin) XXX_Size() int {
	return xxx_messageInfo_InDoneUserLogin.Size(m)
}
func (m *InDoneUserLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_InDoneUserLogin.DiscardUnknown(m)
}

var xxx_messageInfo_InDoneUserLogin proto.InternalMessageInfo

func (m *InDoneUserLogin) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *InDoneUserLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *InDoneUserLogin) GetMobilePhone() string {
	if m != nil {
		return m.MobilePhone
	}
	return ""
}

func (m *InDoneUserLogin) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

func (m *InDoneUserLogin) GetLoginType() uint64 {
	if m != nil {
		return m.LoginType
	}
	return 0
}

type OutDoneUserLogin struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	UserInf              *UserInf `protobuf:"bytes,3,opt,name=user_inf,json=userInf,proto3" json:"user_inf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutDoneUserLogin) Reset()         { *m = OutDoneUserLogin{} }
func (m *OutDoneUserLogin) String() string { return proto.CompactTextString(m) }
func (*OutDoneUserLogin) ProtoMessage()    {}
func (*OutDoneUserLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *OutDoneUserLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutDoneUserLogin.Unmarshal(m, b)
}
func (m *OutDoneUserLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutDoneUserLogin.Marshal(b, m, deterministic)
}
func (m *OutDoneUserLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutDoneUserLogin.Merge(m, src)
}
func (m *OutDoneUserLogin) XXX_Size() int {
	return xxx_messageInfo_OutDoneUserLogin.Size(m)
}
func (m *OutDoneUserLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_OutDoneUserLogin.DiscardUnknown(m)
}

var xxx_messageInfo_OutDoneUserLogin proto.InternalMessageInfo

func (m *OutDoneUserLogin) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *OutDoneUserLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *OutDoneUserLogin) GetUserInf() *UserInf {
	if m != nil {
		return m.UserInf
	}
	return nil
}

type InGetUserInfo struct {
	UserName             string   `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	MobilePhone          string   `protobuf:"bytes,2,opt,name=mobile_phone,json=mobilePhone,proto3" json:"mobile_phone,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InGetUserInfo) Reset()         { *m = InGetUserInfo{} }
func (m *InGetUserInfo) String() string { return proto.CompactTextString(m) }
func (*InGetUserInfo) ProtoMessage()    {}
func (*InGetUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *InGetUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InGetUserInfo.Unmarshal(m, b)
}
func (m *InGetUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InGetUserInfo.Marshal(b, m, deterministic)
}
func (m *InGetUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InGetUserInfo.Merge(m, src)
}
func (m *InGetUserInfo) XXX_Size() int {
	return xxx_messageInfo_InGetUserInfo.Size(m)
}
func (m *InGetUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_InGetUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_InGetUserInfo proto.InternalMessageInfo

func (m *InGetUserInfo) GetUserName() string {
	if m != nil {
		return m.UserName
	}
	return ""
}

func (m *InGetUserInfo) GetMobilePhone() string {
	if m != nil {
		return m.MobilePhone
	}
	return ""
}

func (m *InGetUserInfo) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type OutGetUserInfo struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	UserInf              *UserInf `protobuf:"bytes,2,opt,name=user_inf,json=userInf,proto3" json:"user_inf,omitempty"`
	Roles                []string `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutGetUserInfo) Reset()         { *m = OutGetUserInfo{} }
func (m *OutGetUserInfo) String() string { return proto.CompactTextString(m) }
func (*OutGetUserInfo) ProtoMessage()    {}
func (*OutGetUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *OutGetUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutGetUserInfo.Unmarshal(m, b)
}
func (m *OutGetUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutGetUserInfo.Marshal(b, m, deterministic)
}
func (m *OutGetUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutGetUserInfo.Merge(m, src)
}
func (m *OutGetUserInfo) XXX_Size() int {
	return xxx_messageInfo_OutGetUserInfo.Size(m)
}
func (m *OutGetUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OutGetUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OutGetUserInfo proto.InternalMessageInfo

func (m *OutGetUserInfo) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *OutGetUserInfo) GetUserInf() *UserInf {
	if m != nil {
		return m.UserInf
	}
	return nil
}

func (m *OutGetUserInfo) GetRoles() []string {
	if m != nil {
		return m.Roles
	}
	return nil
}

type InGetUserInfoList struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64    `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	SearchKey            string   `protobuf:"bytes,3,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	StartTime            string   `protobuf:"bytes,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string   `protobuf:"bytes,5,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InGetUserInfoList) Reset()         { *m = InGetUserInfoList{} }
func (m *InGetUserInfoList) String() string { return proto.CompactTextString(m) }
func (*InGetUserInfoList) ProtoMessage()    {}
func (*InGetUserInfoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *InGetUserInfoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InGetUserInfoList.Unmarshal(m, b)
}
func (m *InGetUserInfoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InGetUserInfoList.Marshal(b, m, deterministic)
}
func (m *InGetUserInfoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InGetUserInfoList.Merge(m, src)
}
func (m *InGetUserInfoList) XXX_Size() int {
	return xxx_messageInfo_InGetUserInfoList.Size(m)
}
func (m *InGetUserInfoList) XXX_DiscardUnknown() {
	xxx_messageInfo_InGetUserInfoList.DiscardUnknown(m)
}

var xxx_messageInfo_InGetUserInfoList proto.InternalMessageInfo

func (m *InGetUserInfoList) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *InGetUserInfoList) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *InGetUserInfoList) GetSearchKey() string {
	if m != nil {
		return m.SearchKey
	}
	return ""
}

func (m *InGetUserInfoList) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *InGetUserInfoList) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type OutGetUserInfoList struct {
	Error                *Error     `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit                int64      `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64      `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total                int64      `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	UserInfList          []*UserInf `protobuf:"bytes,5,rep,name=user_inf_list,json=userInfList,proto3" json:"user_inf_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *OutGetUserInfoList) Reset()         { *m = OutGetUserInfoList{} }
func (m *OutGetUserInfoList) String() string { return proto.CompactTextString(m) }
func (*OutGetUserInfoList) ProtoMessage()    {}
func (*OutGetUserInfoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *OutGetUserInfoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutGetUserInfoList.Unmarshal(m, b)
}
func (m *OutGetUserInfoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutGetUserInfoList.Marshal(b, m, deterministic)
}
func (m *OutGetUserInfoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutGetUserInfoList.Merge(m, src)
}
func (m *OutGetUserInfoList) XXX_Size() int {
	return xxx_messageInfo_OutGetUserInfoList.Size(m)
}
func (m *OutGetUserInfoList) XXX_DiscardUnknown() {
	xxx_messageInfo_OutGetUserInfoList.DiscardUnknown(m)
}

var xxx_messageInfo_OutGetUserInfoList proto.InternalMessageInfo

func (m *OutGetUserInfoList) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *OutGetUserInfoList) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *OutGetUserInfoList) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *OutGetUserInfoList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *OutGetUserInfoList) GetUserInfList() []*UserInf {
	if m != nil {
		return m.UserInfList
	}
	return nil
}

type InUpdateUserInfo struct {
	UserInf              *UserInf `protobuf:"bytes,1,opt,name=user_inf,json=userInf,proto3" json:"user_inf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InUpdateUserInfo) Reset()         { *m = InUpdateUserInfo{} }
func (m *InUpdateUserInfo) String() string { return proto.CompactTextString(m) }
func (*InUpdateUserInfo) ProtoMessage()    {}
func (*InUpdateUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *InUpdateUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InUpdateUserInfo.Unmarshal(m, b)
}
func (m *InUpdateUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InUpdateUserInfo.Marshal(b, m, deterministic)
}
func (m *InUpdateUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InUpdateUserInfo.Merge(m, src)
}
func (m *InUpdateUserInfo) XXX_Size() int {
	return xxx_messageInfo_InUpdateUserInfo.Size(m)
}
func (m *InUpdateUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_InUpdateUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_InUpdateUserInfo proto.InternalMessageInfo

func (m *InUpdateUserInfo) GetUserInf() *UserInf {
	if m != nil {
		return m.UserInf
	}
	return nil
}

type OutUpdateUserInfo struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	UserInf              *UserInf `protobuf:"bytes,2,opt,name=user_inf,json=userInf,proto3" json:"user_inf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutUpdateUserInfo) Reset()         { *m = OutUpdateUserInfo{} }
func (m *OutUpdateUserInfo) String() string { return proto.CompactTextString(m) }
func (*OutUpdateUserInfo) ProtoMessage()    {}
func (*OutUpdateUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *OutUpdateUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutUpdateUserInfo.Unmarshal(m, b)
}
func (m *OutUpdateUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutUpdateUserInfo.Marshal(b, m, deterministic)
}
func (m *OutUpdateUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutUpdateUserInfo.Merge(m, src)
}
func (m *OutUpdateUserInfo) XXX_Size() int {
	return xxx_messageInfo_OutUpdateUserInfo.Size(m)
}
func (m *OutUpdateUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OutUpdateUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OutUpdateUserInfo proto.InternalMessageInfo

func (m *OutUpdateUserInfo) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *OutUpdateUserInfo) GetUserInf() *UserInf {
	if m != nil {
		return m.UserInf
	}
	return nil
}

type InDoneUserRegister struct {
	Userinf              *UserInf `protobuf:"bytes,1,opt,name=userinf,proto3" json:"userinf,omitempty"`
	VerificationCode     string   `protobuf:"bytes,2,opt,name=verification_code,json=verificationCode,proto3" json:"verification_code,omitempty"`
	VerificationPhone    string   `protobuf:"bytes,3,opt,name=verification_phone,json=verificationPhone,proto3" json:"verification_phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InDoneUserRegister) Reset()         { *m = InDoneUserRegister{} }
func (m *InDoneUserRegister) String() string { return proto.CompactTextString(m) }
func (*InDoneUserRegister) ProtoMessage()    {}
func (*InDoneUserRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *InDoneUserRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InDoneUserRegister.Unmarshal(m, b)
}
func (m *InDoneUserRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InDoneUserRegister.Marshal(b, m, deterministic)
}
func (m *InDoneUserRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InDoneUserRegister.Merge(m, src)
}
func (m *InDoneUserRegister) XXX_Size() int {
	return xxx_messageInfo_InDoneUserRegister.Size(m)
}
func (m *InDoneUserRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_InDoneUserRegister.DiscardUnknown(m)
}

var xxx_messageInfo_InDoneUserRegister proto.InternalMessageInfo

func (m *InDoneUserRegister) GetUserinf() *UserInf {
	if m != nil {
		return m.Userinf
	}
	return nil
}

func (m *InDoneUserRegister) GetVerificationCode() string {
	if m != nil {
		return m.VerificationCode
	}
	return ""
}

func (m *InDoneUserRegister) GetVerificationPhone() string {
	if m != nil {
		return m.VerificationPhone
	}
	return ""
}

type OutDoneUserRegister struct {
	Token                string   `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	UserInf              *UserInf `protobuf:"bytes,3,opt,name=user_inf,json=userInf,proto3" json:"user_inf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutDoneUserRegister) Reset()         { *m = OutDoneUserRegister{} }
func (m *OutDoneUserRegister) String() string { return proto.CompactTextString(m) }
func (*OutDoneUserRegister) ProtoMessage()    {}
func (*OutDoneUserRegister) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *OutDoneUserRegister) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutDoneUserRegister.Unmarshal(m, b)
}
func (m *OutDoneUserRegister) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutDoneUserRegister.Marshal(b, m, deterministic)
}
func (m *OutDoneUserRegister) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutDoneUserRegister.Merge(m, src)
}
func (m *OutDoneUserRegister) XXX_Size() int {
	return xxx_messageInfo_OutDoneUserRegister.Size(m)
}
func (m *OutDoneUserRegister) XXX_DiscardUnknown() {
	xxx_messageInfo_OutDoneUserRegister.DiscardUnknown(m)
}

var xxx_messageInfo_OutDoneUserRegister proto.InternalMessageInfo

func (m *OutDoneUserRegister) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *OutDoneUserRegister) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *OutDoneUserRegister) GetUserInf() *UserInf {
	if m != nil {
		return m.UserInf
	}
	return nil
}

type InGetVerificationCode struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Telephone            string   `protobuf:"bytes,2,opt,name=telephone,proto3" json:"telephone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InGetVerificationCode) Reset()         { *m = InGetVerificationCode{} }
func (m *InGetVerificationCode) String() string { return proto.CompactTextString(m) }
func (*InGetVerificationCode) ProtoMessage()    {}
func (*InGetVerificationCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{13}
}

func (m *InGetVerificationCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InGetVerificationCode.Unmarshal(m, b)
}
func (m *InGetVerificationCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InGetVerificationCode.Marshal(b, m, deterministic)
}
func (m *InGetVerificationCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InGetVerificationCode.Merge(m, src)
}
func (m *InGetVerificationCode) XXX_Size() int {
	return xxx_messageInfo_InGetVerificationCode.Size(m)
}
func (m *InGetVerificationCode) XXX_DiscardUnknown() {
	xxx_messageInfo_InGetVerificationCode.DiscardUnknown(m)
}

var xxx_messageInfo_InGetVerificationCode proto.InternalMessageInfo

func (m *InGetVerificationCode) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *InGetVerificationCode) GetTelephone() string {
	if m != nil {
		return m.Telephone
	}
	return ""
}

type OutGetVerificationCode struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutGetVerificationCode) Reset()         { *m = OutGetVerificationCode{} }
func (m *OutGetVerificationCode) String() string { return proto.CompactTextString(m) }
func (*OutGetVerificationCode) ProtoMessage()    {}
func (*OutGetVerificationCode) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{14}
}

func (m *OutGetVerificationCode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutGetVerificationCode.Unmarshal(m, b)
}
func (m *OutGetVerificationCode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutGetVerificationCode.Marshal(b, m, deterministic)
}
func (m *OutGetVerificationCode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutGetVerificationCode.Merge(m, src)
}
func (m *OutGetVerificationCode) XXX_Size() int {
	return xxx_messageInfo_OutGetVerificationCode.Size(m)
}
func (m *OutGetVerificationCode) XXX_DiscardUnknown() {
	xxx_messageInfo_OutGetVerificationCode.DiscardUnknown(m)
}

var xxx_messageInfo_OutGetVerificationCode proto.InternalMessageInfo

func (m *OutGetVerificationCode) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type In_GetUserPassengerList struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetUserPassengerList) Reset()         { *m = In_GetUserPassengerList{} }
func (m *In_GetUserPassengerList) String() string { return proto.CompactTextString(m) }
func (*In_GetUserPassengerList) ProtoMessage()    {}
func (*In_GetUserPassengerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{15}
}

func (m *In_GetUserPassengerList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetUserPassengerList.Unmarshal(m, b)
}
func (m *In_GetUserPassengerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetUserPassengerList.Marshal(b, m, deterministic)
}
func (m *In_GetUserPassengerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetUserPassengerList.Merge(m, src)
}
func (m *In_GetUserPassengerList) XXX_Size() int {
	return xxx_messageInfo_In_GetUserPassengerList.Size(m)
}
func (m *In_GetUserPassengerList) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetUserPassengerList.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetUserPassengerList proto.InternalMessageInfo

func (m *In_GetUserPassengerList) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type Out_GetUserPassengerList struct {
	Error                *Error       `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	PassengerList        []*Passenger `protobuf:"bytes,2,rep,name=passenger_list,json=passengerList,proto3" json:"passenger_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Out_GetUserPassengerList) Reset()         { *m = Out_GetUserPassengerList{} }
func (m *Out_GetUserPassengerList) String() string { return proto.CompactTextString(m) }
func (*Out_GetUserPassengerList) ProtoMessage()    {}
func (*Out_GetUserPassengerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{16}
}

func (m *Out_GetUserPassengerList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetUserPassengerList.Unmarshal(m, b)
}
func (m *Out_GetUserPassengerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetUserPassengerList.Marshal(b, m, deterministic)
}
func (m *Out_GetUserPassengerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetUserPassengerList.Merge(m, src)
}
func (m *Out_GetUserPassengerList) XXX_Size() int {
	return xxx_messageInfo_Out_GetUserPassengerList.Size(m)
}
func (m *Out_GetUserPassengerList) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetUserPassengerList.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetUserPassengerList proto.InternalMessageInfo

func (m *Out_GetUserPassengerList) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetUserPassengerList) GetPassengerList() []*Passenger {
	if m != nil {
		return m.PassengerList
	}
	return nil
}

type In_UpdateUserPassenger struct {
	UserId               string       `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PassengerList        []*Passenger `protobuf:"bytes,2,rep,name=passenger_list,json=passengerList,proto3" json:"passenger_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *In_UpdateUserPassenger) Reset()         { *m = In_UpdateUserPassenger{} }
func (m *In_UpdateUserPassenger) String() string { return proto.CompactTextString(m) }
func (*In_UpdateUserPassenger) ProtoMessage()    {}
func (*In_UpdateUserPassenger) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{17}
}

func (m *In_UpdateUserPassenger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_UpdateUserPassenger.Unmarshal(m, b)
}
func (m *In_UpdateUserPassenger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_UpdateUserPassenger.Marshal(b, m, deterministic)
}
func (m *In_UpdateUserPassenger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_UpdateUserPassenger.Merge(m, src)
}
func (m *In_UpdateUserPassenger) XXX_Size() int {
	return xxx_messageInfo_In_UpdateUserPassenger.Size(m)
}
func (m *In_UpdateUserPassenger) XXX_DiscardUnknown() {
	xxx_messageInfo_In_UpdateUserPassenger.DiscardUnknown(m)
}

var xxx_messageInfo_In_UpdateUserPassenger proto.InternalMessageInfo

func (m *In_UpdateUserPassenger) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *In_UpdateUserPassenger) GetPassengerList() []*Passenger {
	if m != nil {
		return m.PassengerList
	}
	return nil
}

type Out_UpdateUserPassenger struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Out_UpdateUserPassenger) Reset()         { *m = Out_UpdateUserPassenger{} }
func (m *Out_UpdateUserPassenger) String() string { return proto.CompactTextString(m) }
func (*Out_UpdateUserPassenger) ProtoMessage()    {}
func (*Out_UpdateUserPassenger) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{18}
}

func (m *Out_UpdateUserPassenger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_UpdateUserPassenger.Unmarshal(m, b)
}
func (m *Out_UpdateUserPassenger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_UpdateUserPassenger.Marshal(b, m, deterministic)
}
func (m *Out_UpdateUserPassenger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_UpdateUserPassenger.Merge(m, src)
}
func (m *Out_UpdateUserPassenger) XXX_Size() int {
	return xxx_messageInfo_Out_UpdateUserPassenger.Size(m)
}
func (m *Out_UpdateUserPassenger) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_UpdateUserPassenger.DiscardUnknown(m)
}

var xxx_messageInfo_Out_UpdateUserPassenger proto.InternalMessageInfo

func (m *Out_UpdateUserPassenger) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type In_Login12306 struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TranUserAccount      string   `protobuf:"bytes,2,opt,name=tran_user_account,json=tranUserAccount,proto3" json:"tran_user_account,omitempty"`
	TranUserPwd          string   `protobuf:"bytes,3,opt,name=tran_user_pwd,json=tranUserPwd,proto3" json:"tran_user_pwd,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_Login12306) Reset()         { *m = In_Login12306{} }
func (m *In_Login12306) String() string { return proto.CompactTextString(m) }
func (*In_Login12306) ProtoMessage()    {}
func (*In_Login12306) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{19}
}

func (m *In_Login12306) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_Login12306.Unmarshal(m, b)
}
func (m *In_Login12306) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_Login12306.Marshal(b, m, deterministic)
}
func (m *In_Login12306) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_Login12306.Merge(m, src)
}
func (m *In_Login12306) XXX_Size() int {
	return xxx_messageInfo_In_Login12306.Size(m)
}
func (m *In_Login12306) XXX_DiscardUnknown() {
	xxx_messageInfo_In_Login12306.DiscardUnknown(m)
}

var xxx_messageInfo_In_Login12306 proto.InternalMessageInfo

func (m *In_Login12306) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *In_Login12306) GetTranUserAccount() string {
	if m != nil {
		return m.TranUserAccount
	}
	return ""
}

func (m *In_Login12306) GetTranUserPwd() string {
	if m != nil {
		return m.TranUserPwd
	}
	return ""
}

type Out_Login12306 struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Out_Login12306) Reset()         { *m = Out_Login12306{} }
func (m *Out_Login12306) String() string { return proto.CompactTextString(m) }
func (*Out_Login12306) ProtoMessage()    {}
func (*Out_Login12306) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{20}
}

func (m *Out_Login12306) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_Login12306.Unmarshal(m, b)
}
func (m *Out_Login12306) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_Login12306.Marshal(b, m, deterministic)
}
func (m *Out_Login12306) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_Login12306.Merge(m, src)
}
func (m *Out_Login12306) XXX_Size() int {
	return xxx_messageInfo_Out_Login12306.Size(m)
}
func (m *Out_Login12306) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_Login12306.DiscardUnknown(m)
}

var xxx_messageInfo_Out_Login12306 proto.InternalMessageInfo

func (m *Out_Login12306) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "user.Error")
	proto.RegisterType((*UserInf)(nil), "user.User_inf")
	proto.RegisterType((*Passenger)(nil), "user.Passenger")
	proto.RegisterType((*InDoneUserLogin)(nil), "user.In_doneUserLogin")
	proto.RegisterType((*OutDoneUserLogin)(nil), "user.Out_doneUserLogin")
	proto.RegisterType((*InGetUserInfo)(nil), "user.In_getUserInfo")
	proto.RegisterType((*OutGetUserInfo)(nil), "user.Out_getUserInfo")
	proto.RegisterType((*InGetUserInfoList)(nil), "user.In_getUserInfoList")
	proto.RegisterType((*OutGetUserInfoList)(nil), "user.Out_getUserInfoList")
	proto.RegisterType((*InUpdateUserInfo)(nil), "user.In_updateUserInfo")
	proto.RegisterType((*OutUpdateUserInfo)(nil), "user.Out_updateUserInfo")
	proto.RegisterType((*InDoneUserRegister)(nil), "user.In_doneUserRegister")
	proto.RegisterType((*OutDoneUserRegister)(nil), "user.Out_doneUserRegister")
	proto.RegisterType((*InGetVerificationCode)(nil), "user.In_getVerificationCode")
	proto.RegisterType((*OutGetVerificationCode)(nil), "user.Out_getVerificationCode")
	proto.RegisterType((*In_GetUserPassengerList)(nil), "user.In_GetUserPassengerList")
	proto.RegisterType((*Out_GetUserPassengerList)(nil), "user.Out_GetUserPassengerList")
	proto.RegisterType((*In_UpdateUserPassenger)(nil), "user.In_UpdateUserPassenger")
	proto.RegisterType((*Out_UpdateUserPassenger)(nil), "user.Out_UpdateUserPassenger")
	proto.RegisterType((*In_Login12306)(nil), "user.In_Login12306")
	proto.RegisterType((*Out_Login12306)(nil), "user.Out_Login12306")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 1521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x58, 0x6b, 0x4f, 0x1b, 0x47,
	0x17, 0xf6, 0x05, 0x83, 0x7d, 0x8c, 0x0d, 0x0c, 0x0e, 0x0c, 0x0e, 0x24, 0x64, 0xdf, 0x8b, 0x78,
	0xdf, 0xb4, 0x69, 0x02, 0x69, 0xa4, 0x4a, 0x51, 0xa5, 0x5c, 0x28, 0x75, 0x13, 0x11, 0xe4, 0x40,
	0xaa, 0x7e, 0x5a, 0x2d, 0xde, 0xc1, 0x19, 0x65, 0x3d, 0x63, 0xed, 0x8e, 0x03, 0xf4, 0x9f, 0x54,
	0xfd, 0x05, 0xed, 0x87, 0xf6, 0x7b, 0x7f, 0x5d, 0x35, 0x67, 0xf6, 0x32, 0x6b, 0x2f, 0x17, 0xf5,
	0x1b, 0xf3, 0x9c, 0x67, 0xce, 0x9e, 0x39, 0xf3, 0x9c, 0x73, 0xc6, 0x00, 0x4c, 0x22, 0x16, 0x3e,
	0x1a, 0x87, 0x52, 0x49, 0x32, 0xa7, 0xff, 0x76, 0xbe, 0x86, 0xda, 0x7e, 0x18, 0xca, 0x90, 0x10,
	0x98, 0x1b, 0x48, 0x9f, 0xd1, 0xf2, 0x76, 0x79, 0xa7, 0xd6, 0xc7, 0xbf, 0x09, 0x85, 0x85, 0x11,
	0x8b, 0x22, 0x6f, 0xc8, 0x68, 0x65, 0xbb, 0xbc, 0xd3, 0xe8, 0x27, 0x4b, 0xe7, 0xb7, 0x39, 0xa8,
	0x9f, 0x44, 0x2c, 0x74, 0xb9, 0x38, 0x23, 0xeb, 0xb0, 0x30, 0xc1, 0xbf, 0x7d, 0xdc, 0xdd, 0xe8,
	0xcf, 0xeb, 0x65, 0xcf, 0x27, 0x77, 0xa1, 0x21, 0xf8, 0x27, 0xe6, 0x0a, 0x6f, 0x94, 0x78, 0xa8,
	0x6b, 0xe0, 0xd0, 0x1b, 0x31, 0x6d, 0xc4, 0x5d, 0x68, 0xac, 0x1a, 0xa3, 0x06, 0xd0, 0xd8, 0x85,
	0xfa, 0xd8, 0x8b, 0xa2, 0x73, 0x19, 0xfa, 0x74, 0xce, 0xd8, 0x92, 0x35, 0xd9, 0x32, 0xc7, 0x70,
	0x23, 0xe5, 0xa9, 0x88, 0xd6, 0xb6, 0xcb, 0x3b, 0x73, 0x7d, 0x74, 0xf5, 0x5e, 0x03, 0xe4, 0x0b,
	0x20, 0xdc, 0x67, 0x42, 0x71, 0x75, 0xe9, 0x0e, 0xbc, 0xd0, 0x77, 0xd5, 0xe5, 0x98, 0xd1, 0x79,
	0xa4, 0x2d, 0x27, 0x96, 0x57, 0x5e, 0xe8, 0x1f, 0x5f, 0x8e, 0x19, 0xd9, 0x81, 0xe5, 0x3c, 0x5b,
	0x48, 0xba, 0x80, 0x1f, 0x6c, 0xdb, 0xdc, 0x43, 0x49, 0x1e, 0xc0, 0xe2, 0x48, 0x9e, 0xf2, 0x80,
	0xb9, 0xe3, 0x8f, 0x52, 0x30, 0x5a, 0x47, 0x56, 0xd3, 0x60, 0x47, 0x1a, 0x4a, 0x23, 0x63, 0x23,
	0x8f, 0x07, 0xb4, 0x81, 0x04, 0x8c, 0x6c, 0x5f, 0x03, 0x64, 0x0d, 0xe6, 0x87, 0x4c, 0xf8, 0x2c,
	0xa4, 0x60, 0xd2, 0x64, 0x56, 0xe9, 0xb6, 0xb1, 0xe4, 0x42, 0xd1, 0x66, 0x76, 0xa0, 0x23, 0x0d,
	0x90, 0x7f, 0x41, 0x2b, 0x64, 0x43, 0x1e, 0x29, 0x16, 0xba, 0x8a, 0x8f, 0x18, 0x5d, 0xc4, 0xdd,
	0x8b, 0x09, 0x78, 0xcc, 0x47, 0x4c, 0x93, 0x46, 0xd2, 0xe7, 0x67, 0x9c, 0xf9, 0x86, 0xd4, 0x36,
	0xa4, 0x04, 0x44, 0xd2, 0xbf, 0xa1, 0xad, 0x42, 0x4f, 0xb8, 0x59, 0xde, 0x97, 0x0c, 0x4b, 0xa3,
	0x27, 0x49, 0xee, 0xff, 0x0f, 0x2b, 0x19, 0xcb, 0x1b, 0x0c, 0xe4, 0x44, 0x28, 0xba, 0x8c, 0xc4,
	0xa5, 0x84, 0xf8, 0xc2, 0xc0, 0xc4, 0x81, 0x56, 0xc6, 0x1d, 0x9f, 0xfb, 0x74, 0xc5, 0x64, 0x25,
	0xe1, 0x1d, 0x9d, 0xfb, 0xce, 0x9f, 0x75, 0x68, 0x1c, 0x79, 0x51, 0xc4, 0xc4, 0x90, 0x85, 0xa4,
	0x0d, 0x95, 0x54, 0x27, 0x15, 0xee, 0xdb, 0xe2, 0xa9, 0xe4, 0xc4, 0xf3, 0x1f, 0x68, 0x8f, 0x93,
	0x5d, 0xb6, 0x48, 0x5a, 0x29, 0x8a, 0xd1, 0x6e, 0x40, 0x3d, 0x62, 0x17, 0x2e, 0x6a, 0xd7, 0x28,
	0x65, 0x21, 0x62, 0x17, 0xaf, 0xb4, 0x7c, 0x63, 0x13, 0xee, 0xad, 0xa5, 0xa6, 0x44, 0x7c, 0xa7,
	0x32, 0x14, 0xae, 0xef, 0x29, 0xa3, 0x8d, 0x46, 0xbf, 0xae, 0x81, 0xd7, 0x9e, 0x62, 0xfa, 0xa6,
	0xf1, 0x74, 0xe1, 0xa5, 0x71, 0x6b, 0xf4, 0xd0, 0x8c, 0x31, 0x74, 0xbd, 0x07, 0x6b, 0x59, 0x70,
	0xdc, 0x68, 0xcc, 0x90, 0x8d, 0x2c, 0x56, 0x53, 0x6b, 0x0f, 0x75, 0x76, 0xf5, 0x26, 0x8c, 0xae,
	0x51, 0xb8, 0x09, 0x23, 0xfd, 0x2f, 0x2c, 0xe5, 0x36, 0x09, 0x19, 0xab, 0xa7, 0x65, 0xb1, 0x0f,
	0x65, 0x3e, 0x5d, 0x28, 0xf9, 0xe6, 0x14, 0x0d, 0xf5, 0x9e, 0xa3, 0x9d, 0x05, 0xde, 0x30, 0x56,
	0x53, 0x46, 0xfb, 0x2e, 0xf0, 0x86, 0xe4, 0x11, 0xac, 0xe6, 0xbd, 0x99, 0x38, 0x5b, 0xc8, 0x5d,
	0xc9, 0xb9, 0x4c, 0xf2, 0x19, 0x17, 0x87, 0x90, 0xb1, 0xf4, 0xea, 0x06, 0x38, 0x94, 0xfa, 0x1e,
	0xb0, 0x64, 0xb4, 0xcd, 0x08, 0x6e, 0x01, 0xd7, 0x87, 0x92, 0x74, 0xa0, 0x66, 0x8a, 0xc5, 0xe8,
	0xcb, 0x2c, 0x74, 0xdf, 0xf1, 0x7c, 0x3f, 0x64, 0x51, 0x14, 0xeb, 0x29, 0x59, 0x92, 0x7b, 0x00,
	0x63, 0x19, 0x29, 0x2f, 0xc0, 0x5c, 0x13, 0x34, 0x5a, 0x88, 0xbe, 0xba, 0x33, 0x1e, 0x46, 0xca,
	0x0d, 0x98, 0x52, 0x2c, 0xa4, 0xab, 0xe6, 0xea, 0x10, 0x7b, 0x8b, 0x10, 0xd9, 0x86, 0x66, 0xc8,
	0x06, 0x32, 0xf4, 0x5f, 0xa1, 0xb0, 0x3b, 0x86, 0x61, 0x41, 0xe4, 0x3e, 0x34, 0x95, 0x54, 0x5e,
	0x80, 0x85, 0x14, 0xd1, 0x3b, 0xe6, 0x2b, 0x08, 0xe9, 0x32, 0x8a, 0xf4, 0x81, 0xb8, 0xf0, 0xd9,
	0x85, 0x16, 0xed, 0x9a, 0x09, 0x10, 0xd7, 0x3d, 0x9f, 0x6c, 0x42, 0xc3, 0x0b, 0x82, 0x7d, 0x31,
	0x78, 0xaf, 0x42, 0xba, 0x6e, 0x3a, 0x40, 0x0a, 0xe8, 0x83, 0xf1, 0xe8, 0x85, 0x3f, 0x09, 0x14,
	0xa5, 0xf1, 0x3e, 0xb3, 0x24, 0x0e, 0x2c, 0xf2, 0xe8, 0x27, 0x29, 0x86, 0xc7, 0x1f, 0x3d, 0xf1,
	0xe4, 0x31, 0xdd, 0x30, 0x85, 0x69, 0x63, 0x53, 0x9c, 0xa7, 0xb4, 0x3b, 0xc3, 0x79, 0xaa, 0x4f,
	0xc7, 0xa3, 0x77, 0x81, 0xaf, 0x97, 0xcf, 0x1e, 0xd3, 0xbb, 0xe6, 0x74, 0x16, 0xa4, 0x4b, 0x76,
	0xe8, 0x29, 0x37, 0x93, 0xff, 0xa6, 0xe1, 0x0c, 0x3d, 0xf5, 0x32, 0xa9, 0x80, 0xaf, 0xa0, 0xa3,
	0x39, 0x9f, 0xbd, 0x80, 0xfb, 0x48, 0xd2, 0xcd, 0x36, 0x54, 0x74, 0xcb, 0xdc, 0xff, 0xd0, 0x53,
	0x1f, 0xb4, 0x49, 0x73, 0xdf, 0x6b, 0x03, 0x79, 0x08, 0x64, 0x6a, 0x03, 0x13, 0x3e, 0xbd, 0x67,
	0x9a, 0x86, 0x4d, 0xdf, 0x17, 0xbe, 0xce, 0x2f, 0x92, 0x59, 0x18, 0x71, 0x29, 0xe8, 0x7d, 0x93,
	0x5f, 0xcd, 0x32, 0x88, 0xf3, 0x57, 0x19, 0x96, 0x7b, 0xc2, 0xf5, 0xa5, 0x60, 0xba, 0x89, 0xbc,
	0x95, 0x43, 0x2e, 0xf2, 0xf3, 0xa2, 0x7c, 0xcd, 0xbc, 0xa8, 0x4c, 0xcd, 0x8b, 0xe9, 0xc6, 0x5d,
	0x9d, 0x6d, 0xdc, 0x0f, 0x61, 0xe5, 0x33, 0x0b, 0xf9, 0x19, 0x1f, 0x78, 0x8a, 0x4b, 0x61, 0x77,
	0x93, 0x65, 0xdb, 0x80, 0x65, 0xbc, 0x05, 0x10, 0xe8, 0x88, 0x4c, 0x95, 0xc5, 0xf3, 0x07, 0x11,
	0x5d, 0x0e, 0xce, 0x39, 0xac, 0xbc, 0x9b, 0xa8, 0xa9, 0xe0, 0x1f, 0xc4, 0x63, 0x16, 0x03, 0x6f,
	0xee, 0x36, 0x1f, 0xe1, 0x20, 0x46, 0xa8, 0x1f, 0x0f, 0xe0, 0x0e, 0xd4, 0x94, 0xfc, 0xc4, 0x44,
	0x1c, 0xbf, 0x59, 0x90, 0xff, 0x41, 0x7d, 0x12, 0xcf, 0x59, 0x0c, 0xbc, 0xb9, 0xdb, 0x36, 0x7b,
	0x93, 0xe9, 0xdb, 0xc7, 0xf6, 0xd9, 0x13, 0x67, 0x0e, 0x87, 0x76, 0x4f, 0xb8, 0x43, 0xa6, 0x4e,
	0x0c, 0x20, 0xaf, 0x4f, 0xd9, 0x74, 0x5a, 0x2a, 0xb3, 0x69, 0xb1, 0x7a, 0x73, 0xd5, 0xee, 0xcd,
	0xce, 0x04, 0x96, 0xf4, 0x19, 0xed, 0x6f, 0x3d, 0x80, 0x1a, 0xbb, 0xf2, 0x84, 0x68, 0xc9, 0x9d,
	0xa5, 0x72, 0xed, 0x59, 0x74, 0x32, 0x42, 0x19, 0xb0, 0x88, 0x56, 0xb7, 0xab, 0x3a, 0x19, 0xb8,
	0x70, 0x7e, 0x29, 0x03, 0xc9, 0x1f, 0xf1, 0x2d, 0x8f, 0x94, 0x26, 0x07, 0x7c, 0xc4, 0x15, 0x7e,
	0xba, 0xda, 0x37, 0x0b, 0x8d, 0x8e, 0xbd, 0x21, 0x8b, 0xf0, 0x53, 0xd5, 0xbe, 0x59, 0xe8, 0xcb,
	0x8b, 0x98, 0x17, 0x0e, 0x3e, 0xba, 0x9f, 0xd8, 0x65, 0x7c, 0xaa, 0x86, 0x41, 0xde, 0xb0, 0x4b,
	0x34, 0x6b, 0x41, 0x9b, 0x19, 0x3a, 0x17, 0x9b, 0x35, 0x82, 0x03, 0x74, 0x03, 0xea, 0x4c, 0xc4,
	0x03, 0x36, 0x9e, 0x28, 0x4c, 0xe0, 0x6c, 0x75, 0xfe, 0x28, 0xc3, 0xea, 0x54, 0x4e, 0x30, 0xb8,
	0x5b, 0xe4, 0x25, 0x8d, 0xbf, 0x52, 0x18, 0x7f, 0xd5, 0x8e, 0x1f, 0x55, 0xa2, 0xbc, 0x00, 0x63,
	0xab, 0xf6, 0xcd, 0x82, 0xec, 0x42, 0x2b, 0xc9, 0xac, 0x1b, 0xf0, 0x48, 0xd1, 0xda, 0x76, 0xb5,
	0x20, 0xbd, 0xcd, 0x38, 0xbd, 0x3a, 0x30, 0xe7, 0x5b, 0x58, 0xe9, 0x09, 0x77, 0x32, 0xd6, 0xd5,
	0x9a, 0xde, 0xa2, 0x7d, 0x45, 0xe5, 0xeb, 0xe5, 0x76, 0x0a, 0x44, 0x9f, 0x77, 0xca, 0xc1, 0x2d,
	0x84, 0x7e, 0x7b, 0x19, 0x38, 0xbf, 0x96, 0x61, 0xd5, 0x6a, 0x04, 0xfd, 0xf8, 0xc5, 0x43, 0x76,
	0x8c, 0x30, 0x6f, 0x88, 0x52, 0xbf, 0x4d, 0x0b, 0x2b, 0xbb, 0x72, 0x45, 0x65, 0x7f, 0x09, 0x24,
	0x47, 0xb6, 0xfb, 0x45, 0xce, 0x0d, 0x96, 0x87, 0xf3, 0x33, 0x74, 0xec, 0x4a, 0x4f, 0xa3, 0xeb,
	0x40, 0xed, 0x18, 0x2b, 0xd9, 0x94, 0x9c, 0x59, 0x64, 0x99, 0xa9, 0xdc, 0x2a, 0x33, 0x37, 0x14,
	0xfb, 0x0f, 0xb0, 0x66, 0x2a, 0xe1, 0xc3, 0xf4, 0x21, 0xec, 0x87, 0x7c, 0x23, 0x7e, 0xc8, 0x6f,
	0x42, 0x43, 0xb1, 0x80, 0xd9, 0x85, 0x9e, 0x01, 0xce, 0x73, 0x58, 0x8f, 0x95, 0x3b, 0xe3, 0xec,
	0xe6, 0xeb, 0x74, 0x76, 0x61, 0xbd, 0x27, 0xdc, 0x03, 0x23, 0xfb, 0xf4, 0x9d, 0x87, 0xda, 0xbf,
	0xea, 0x87, 0x81, 0x33, 0x01, 0xaa, 0xbf, 0x58, 0xb8, 0xe9, 0x16, 0x0a, 0x7a, 0x66, 0x3f, 0x62,
	0x50, 0xef, 0x15, 0xd4, 0xfb, 0x92, 0xe1, 0xa6, 0xfe, 0xac, 0x57, 0x0d, 0x4a, 0x9e, 0x63, 0xd2,
	0x4e, 0x52, 0xc5, 0x66, 0xaf, 0xd2, 0x2b, 0x7f, 0xc2, 0xfc, 0xd3, 0x4f, 0xc5, 0x39, 0x2d, 0xfa,
	0xd6, 0x2d, 0x72, 0x7a, 0x01, 0xad, 0x9e, 0x70, 0x71, 0x74, 0x3c, 0xd9, 0xdd, 0x7b, 0xfc, 0xec,
	0xea, 0xf8, 0x0a, 0x1f, 0xeb, 0x95, 0x5b, 0x3e, 0xd6, 0xab, 0xb3, 0x8f, 0xf5, 0x3d, 0x68, 0xeb,
	0xb8, 0xad, 0x4f, 0xdf, 0x1c, 0xee, 0xee, 0xef, 0x35, 0xf3, 0x6b, 0x10, 0x3b, 0xc0, 0x4b, 0x68,
	0xbd, 0xce, 0xcd, 0xbe, 0x35, 0xb3, 0x63, 0x7a, 0xa0, 0x77, 0xd7, 0x0d, 0x3e, 0x33, 0x2c, 0x9d,
	0x12, 0x79, 0x0e, 0xcd, 0x03, 0x6b, 0xb6, 0x74, 0x52, 0x0f, 0x56, 0x77, 0xed, 0xde, 0xc9, 0xf6,
	0x5b, 0xb0, 0x53, 0x22, 0xdf, 0xc3, 0xd2, 0xc1, 0x54, 0x17, 0xa6, 0x45, 0x1e, 0xb4, 0xa5, 0xbb,
	0x51, 0xe8, 0x05, 0xef, 0xb0, 0x44, 0xf6, 0xa1, 0x7d, 0x92, 0xef, 0x6f, 0xeb, 0xa9, 0xa3, 0x7c,
	0xe3, 0xeb, 0xd2, 0xcc, 0x4f, 0xde, 0xe2, 0x94, 0xc8, 0x1b, 0x58, 0x7e, 0x3d, 0xdd, 0x24, 0x36,
	0x66, 0xb2, 0x92, 0x98, 0xba, 0xdd, 0xd9, 0xc4, 0x24, 0x36, 0xa7, 0x44, 0x8e, 0x61, 0xf5, 0xa0,
	0xa0, 0x52, 0x37, 0xed, 0x13, 0x4e, 0x5b, 0xbb, 0x5b, 0xb9, 0x53, 0x4e, 0x9b, 0x9d, 0x12, 0xf9,
	0x11, 0x3a, 0x85, 0xd5, 0xb8, 0x95, 0xba, 0x2d, 0x32, 0x77, 0xef, 0x65, 0x7e, 0x8b, 0xec, 0x26,
	0xdc, 0xa2, 0x22, 0xc8, 0xc2, 0x2d, 0xb0, 0xda, 0xe1, 0x16, 0x98, 0x9d, 0x12, 0xf9, 0x06, 0xc0,
	0x92, 0xe8, 0x6a, 0xea, 0x2c, 0x03, 0xbb, 0x9d, 0xcc, 0x47, 0x86, 0x3a, 0xa5, 0xd3, 0x79, 0xfc,
	0xf7, 0xc7, 0xde, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x7a, 0xcf, 0x1c, 0xb6, 0x0c, 0x11, 0x00,
	0x00,
}
