// Code generated by protoc-gen-go. DO NOT EDIT.
// source: ticket.proto

package ticket

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a6c21780e82d22, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Train struct {
	SecretStr            string   `protobuf:"bytes,1,opt,name=secret_str,json=secretStr,proto3" json:"secret_str,omitempty"`
	TrainCode            string   `protobuf:"bytes,2,opt,name=train_code,json=trainCode,proto3" json:"train_code,omitempty"`
	Num                  string   `protobuf:"bytes,3,opt,name=num,proto3" json:"num,omitempty"`
	From                 string   `protobuf:"bytes,4,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,5,opt,name=to,proto3" json:"to,omitempty"`
	FindFrom             string   `protobuf:"bytes,6,opt,name=find_from,json=findFrom,proto3" json:"find_from,omitempty"`
	FindTo               string   `protobuf:"bytes,7,opt,name=find_to,json=findTo,proto3" json:"find_to,omitempty"`
	StartTime            string   `protobuf:"bytes,8,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string   `protobuf:"bytes,9,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	CostTime             string   `protobuf:"bytes,10,opt,name=cost_time,json=costTime,proto3" json:"cost_time,omitempty"`
	CanBuy               string   `protobuf:"bytes,11,opt,name=can_buy,json=canBuy,proto3" json:"can_buy,omitempty"`
	TrainDate            string   `protobuf:"bytes,12,opt,name=train_date,json=trainDate,proto3" json:"train_date,omitempty"`
	Swtdz                string   `protobuf:"bytes,13,opt,name=swtdz,proto3" json:"swtdz,omitempty"`
	Ydz                  string   `protobuf:"bytes,14,opt,name=ydz,proto3" json:"ydz,omitempty"`
	Edz                  string   `protobuf:"bytes,15,opt,name=edz,proto3" json:"edz,omitempty"`
	Gjrw                 string   `protobuf:"bytes,16,opt,name=gjrw,proto3" json:"gjrw,omitempty"`
	Rw                   string   `protobuf:"bytes,17,opt,name=rw,proto3" json:"rw,omitempty"`
	Dw                   string   `protobuf:"bytes,18,opt,name=dw,proto3" json:"dw,omitempty"`
	Yw                   string   `protobuf:"bytes,19,opt,name=yw,proto3" json:"yw,omitempty"`
	Rz                   string   `protobuf:"bytes,20,opt,name=rz,proto3" json:"rz,omitempty"`
	Yz                   string   `protobuf:"bytes,21,opt,name=yz,proto3" json:"yz,omitempty"`
	Wz                   string   `protobuf:"bytes,22,opt,name=wz,proto3" json:"wz,omitempty"`
	Qt                   string   `protobuf:"bytes,23,opt,name=qt,proto3" json:"qt,omitempty"`
	Bz                   string   `protobuf:"bytes,24,opt,name=bz,proto3" json:"bz,omitempty"`
	PurposeCodes         string   `protobuf:"bytes,25,opt,name=purpose_codes,json=purposeCodes,proto3" json:"purpose_codes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Train) Reset()         { *m = Train{} }
func (m *Train) String() string { return proto.CompactTextString(m) }
func (*Train) ProtoMessage()    {}
func (*Train) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a6c21780e82d22, []int{1}
}

func (m *Train) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Train.Unmarshal(m, b)
}
func (m *Train) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Train.Marshal(b, m, deterministic)
}
func (m *Train) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Train.Merge(m, src)
}
func (m *Train) XXX_Size() int {
	return xxx_messageInfo_Train.Size(m)
}
func (m *Train) XXX_DiscardUnknown() {
	xxx_messageInfo_Train.DiscardUnknown(m)
}

var xxx_messageInfo_Train proto.InternalMessageInfo

func (m *Train) GetSecretStr() string {
	if m != nil {
		return m.SecretStr
	}
	return ""
}

func (m *Train) GetTrainCode() string {
	if m != nil {
		return m.TrainCode
	}
	return ""
}

func (m *Train) GetNum() string {
	if m != nil {
		return m.Num
	}
	return ""
}

func (m *Train) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Train) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Train) GetFindFrom() string {
	if m != nil {
		return m.FindFrom
	}
	return ""
}

func (m *Train) GetFindTo() string {
	if m != nil {
		return m.FindTo
	}
	return ""
}

func (m *Train) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *Train) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

func (m *Train) GetCostTime() string {
	if m != nil {
		return m.CostTime
	}
	return ""
}

func (m *Train) GetCanBuy() string {
	if m != nil {
		return m.CanBuy
	}
	return ""
}

func (m *Train) GetTrainDate() string {
	if m != nil {
		return m.TrainDate
	}
	return ""
}

func (m *Train) GetSwtdz() string {
	if m != nil {
		return m.Swtdz
	}
	return ""
}

func (m *Train) GetYdz() string {
	if m != nil {
		return m.Ydz
	}
	return ""
}

func (m *Train) GetEdz() string {
	if m != nil {
		return m.Edz
	}
	return ""
}

func (m *Train) GetGjrw() string {
	if m != nil {
		return m.Gjrw
	}
	return ""
}

func (m *Train) GetRw() string {
	if m != nil {
		return m.Rw
	}
	return ""
}

func (m *Train) GetDw() string {
	if m != nil {
		return m.Dw
	}
	return ""
}

func (m *Train) GetYw() string {
	if m != nil {
		return m.Yw
	}
	return ""
}

func (m *Train) GetRz() string {
	if m != nil {
		return m.Rz
	}
	return ""
}

func (m *Train) GetYz() string {
	if m != nil {
		return m.Yz
	}
	return ""
}

func (m *Train) GetWz() string {
	if m != nil {
		return m.Wz
	}
	return ""
}

func (m *Train) GetQt() string {
	if m != nil {
		return m.Qt
	}
	return ""
}

func (m *Train) GetBz() string {
	if m != nil {
		return m.Bz
	}
	return ""
}

func (m *Train) GetPurposeCodes() string {
	if m != nil {
		return m.PurposeCodes
	}
	return ""
}

type In_GetTrainInfo struct {
	SecretStr            string   `protobuf:"bytes,1,opt,name=secret_str,json=secretStr,proto3" json:"secret_str,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetTrainInfo) Reset()         { *m = In_GetTrainInfo{} }
func (m *In_GetTrainInfo) String() string { return proto.CompactTextString(m) }
func (*In_GetTrainInfo) ProtoMessage()    {}
func (*In_GetTrainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a6c21780e82d22, []int{2}
}

func (m *In_GetTrainInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetTrainInfo.Unmarshal(m, b)
}
func (m *In_GetTrainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetTrainInfo.Marshal(b, m, deterministic)
}
func (m *In_GetTrainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetTrainInfo.Merge(m, src)
}
func (m *In_GetTrainInfo) XXX_Size() int {
	return xxx_messageInfo_In_GetTrainInfo.Size(m)
}
func (m *In_GetTrainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetTrainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetTrainInfo proto.InternalMessageInfo

func (m *In_GetTrainInfo) GetSecretStr() string {
	if m != nil {
		return m.SecretStr
	}
	return ""
}

type Out_GetTrainInfo struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Train                *Train   `protobuf:"bytes,2,opt,name=train,proto3" json:"train,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Out_GetTrainInfo) Reset()         { *m = Out_GetTrainInfo{} }
func (m *Out_GetTrainInfo) String() string { return proto.CompactTextString(m) }
func (*Out_GetTrainInfo) ProtoMessage()    {}
func (*Out_GetTrainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a6c21780e82d22, []int{3}
}

func (m *Out_GetTrainInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetTrainInfo.Unmarshal(m, b)
}
func (m *Out_GetTrainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetTrainInfo.Marshal(b, m, deterministic)
}
func (m *Out_GetTrainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetTrainInfo.Merge(m, src)
}
func (m *Out_GetTrainInfo) XXX_Size() int {
	return xxx_messageInfo_Out_GetTrainInfo.Size(m)
}
func (m *Out_GetTrainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetTrainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetTrainInfo proto.InternalMessageInfo

func (m *Out_GetTrainInfo) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetTrainInfo) GetTrain() *Train {
	if m != nil {
		return m.Train
	}
	return nil
}

type In_GetTrainInfoList struct {
	FindFrom             string   `protobuf:"bytes,1,opt,name=find_from,json=findFrom,proto3" json:"find_from,omitempty"`
	FindTo               string   `protobuf:"bytes,2,opt,name=find_to,json=findTo,proto3" json:"find_to,omitempty"`
	TrainDate            string   `protobuf:"bytes,3,opt,name=train_date,json=trainDate,proto3" json:"train_date,omitempty"`
	PurposeCodes         string   `protobuf:"bytes,4,opt,name=purpose_codes,json=purposeCodes,proto3" json:"purpose_codes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetTrainInfoList) Reset()         { *m = In_GetTrainInfoList{} }
func (m *In_GetTrainInfoList) String() string { return proto.CompactTextString(m) }
func (*In_GetTrainInfoList) ProtoMessage()    {}
func (*In_GetTrainInfoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a6c21780e82d22, []int{4}
}

func (m *In_GetTrainInfoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetTrainInfoList.Unmarshal(m, b)
}
func (m *In_GetTrainInfoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetTrainInfoList.Marshal(b, m, deterministic)
}
func (m *In_GetTrainInfoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetTrainInfoList.Merge(m, src)
}
func (m *In_GetTrainInfoList) XXX_Size() int {
	return xxx_messageInfo_In_GetTrainInfoList.Size(m)
}
func (m *In_GetTrainInfoList) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetTrainInfoList.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetTrainInfoList proto.InternalMessageInfo

func (m *In_GetTrainInfoList) GetFindFrom() string {
	if m != nil {
		return m.FindFrom
	}
	return ""
}

func (m *In_GetTrainInfoList) GetFindTo() string {
	if m != nil {
		return m.FindTo
	}
	return ""
}

func (m *In_GetTrainInfoList) GetTrainDate() string {
	if m != nil {
		return m.TrainDate
	}
	return ""
}

func (m *In_GetTrainInfoList) GetPurposeCodes() string {
	if m != nil {
		return m.PurposeCodes
	}
	return ""
}

type Out_GetTrainInfoList struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64    `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total                int64    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	TrainList            []*Train `protobuf:"bytes,5,rep,name=train_list,json=trainList,proto3" json:"train_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Out_GetTrainInfoList) Reset()         { *m = Out_GetTrainInfoList{} }
func (m *Out_GetTrainInfoList) String() string { return proto.CompactTextString(m) }
func (*Out_GetTrainInfoList) ProtoMessage()    {}
func (*Out_GetTrainInfoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a6c21780e82d22, []int{5}
}

func (m *Out_GetTrainInfoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetTrainInfoList.Unmarshal(m, b)
}
func (m *Out_GetTrainInfoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetTrainInfoList.Marshal(b, m, deterministic)
}
func (m *Out_GetTrainInfoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetTrainInfoList.Merge(m, src)
}
func (m *Out_GetTrainInfoList) XXX_Size() int {
	return xxx_messageInfo_Out_GetTrainInfoList.Size(m)
}
func (m *Out_GetTrainInfoList) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetTrainInfoList.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetTrainInfoList proto.InternalMessageInfo

func (m *Out_GetTrainInfoList) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetTrainInfoList) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Out_GetTrainInfoList) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *Out_GetTrainInfoList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Out_GetTrainInfoList) GetTrainList() []*Train {
	if m != nil {
		return m.TrainList
	}
	return nil
}

type In_UpdateTrainInfo struct {
	Train                *Train   `protobuf:"bytes,1,opt,name=Train,proto3" json:"Train,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_UpdateTrainInfo) Reset()         { *m = In_UpdateTrainInfo{} }
func (m *In_UpdateTrainInfo) String() string { return proto.CompactTextString(m) }
func (*In_UpdateTrainInfo) ProtoMessage()    {}
func (*In_UpdateTrainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a6c21780e82d22, []int{6}
}

func (m *In_UpdateTrainInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_UpdateTrainInfo.Unmarshal(m, b)
}
func (m *In_UpdateTrainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_UpdateTrainInfo.Marshal(b, m, deterministic)
}
func (m *In_UpdateTrainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_UpdateTrainInfo.Merge(m, src)
}
func (m *In_UpdateTrainInfo) XXX_Size() int {
	return xxx_messageInfo_In_UpdateTrainInfo.Size(m)
}
func (m *In_UpdateTrainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_In_UpdateTrainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_In_UpdateTrainInfo proto.InternalMessageInfo

func (m *In_UpdateTrainInfo) GetTrain() *Train {
	if m != nil {
		return m.Train
	}
	return nil
}

type Out_UpdateTrainInfo struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Train                *Train   `protobuf:"bytes,2,opt,name=train,proto3" json:"train,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Out_UpdateTrainInfo) Reset()         { *m = Out_UpdateTrainInfo{} }
func (m *Out_UpdateTrainInfo) String() string { return proto.CompactTextString(m) }
func (*Out_UpdateTrainInfo) ProtoMessage()    {}
func (*Out_UpdateTrainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a6c21780e82d22, []int{7}
}

func (m *Out_UpdateTrainInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_UpdateTrainInfo.Unmarshal(m, b)
}
func (m *Out_UpdateTrainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_UpdateTrainInfo.Marshal(b, m, deterministic)
}
func (m *Out_UpdateTrainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_UpdateTrainInfo.Merge(m, src)
}
func (m *Out_UpdateTrainInfo) XXX_Size() int {
	return xxx_messageInfo_Out_UpdateTrainInfo.Size(m)
}
func (m *Out_UpdateTrainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_UpdateTrainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Out_UpdateTrainInfo proto.InternalMessageInfo

func (m *Out_UpdateTrainInfo) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_UpdateTrainInfo) GetTrain() *Train {
	if m != nil {
		return m.Train
	}
	return nil
}

type In_AddTrain struct {
	Train                *Train   `protobuf:"bytes,1,opt,name=train,proto3" json:"train,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_AddTrain) Reset()         { *m = In_AddTrain{} }
func (m *In_AddTrain) String() string { return proto.CompactTextString(m) }
func (*In_AddTrain) ProtoMessage()    {}
func (*In_AddTrain) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a6c21780e82d22, []int{8}
}

func (m *In_AddTrain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_AddTrain.Unmarshal(m, b)
}
func (m *In_AddTrain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_AddTrain.Marshal(b, m, deterministic)
}
func (m *In_AddTrain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_AddTrain.Merge(m, src)
}
func (m *In_AddTrain) XXX_Size() int {
	return xxx_messageInfo_In_AddTrain.Size(m)
}
func (m *In_AddTrain) XXX_DiscardUnknown() {
	xxx_messageInfo_In_AddTrain.DiscardUnknown(m)
}

var xxx_messageInfo_In_AddTrain proto.InternalMessageInfo

func (m *In_AddTrain) GetTrain() *Train {
	if m != nil {
		return m.Train
	}
	return nil
}

type Out_AddTrain struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	Train                *Train   `protobuf:"bytes,2,opt,name=train,proto3" json:"train,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Out_AddTrain) Reset()         { *m = Out_AddTrain{} }
func (m *Out_AddTrain) String() string { return proto.CompactTextString(m) }
func (*Out_AddTrain) ProtoMessage()    {}
func (*Out_AddTrain) Descriptor() ([]byte, []int) {
	return fileDescriptor_98a6c21780e82d22, []int{9}
}

func (m *Out_AddTrain) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_AddTrain.Unmarshal(m, b)
}
func (m *Out_AddTrain) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_AddTrain.Marshal(b, m, deterministic)
}
func (m *Out_AddTrain) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_AddTrain.Merge(m, src)
}
func (m *Out_AddTrain) XXX_Size() int {
	return xxx_messageInfo_Out_AddTrain.Size(m)
}
func (m *Out_AddTrain) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_AddTrain.DiscardUnknown(m)
}

var xxx_messageInfo_Out_AddTrain proto.InternalMessageInfo

func (m *Out_AddTrain) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_AddTrain) GetTrain() *Train {
	if m != nil {
		return m.Train
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "ticket.Error")
	proto.RegisterType((*Train)(nil), "ticket.Train")
	proto.RegisterType((*In_GetTrainInfo)(nil), "ticket.In_GetTrainInfo")
	proto.RegisterType((*Out_GetTrainInfo)(nil), "ticket.Out_GetTrainInfo")
	proto.RegisterType((*In_GetTrainInfoList)(nil), "ticket.In_GetTrainInfoList")
	proto.RegisterType((*Out_GetTrainInfoList)(nil), "ticket.Out_GetTrainInfoList")
	proto.RegisterType((*In_UpdateTrainInfo)(nil), "ticket.In_UpdateTrainInfo")
	proto.RegisterType((*Out_UpdateTrainInfo)(nil), "ticket.Out_UpdateTrainInfo")
	proto.RegisterType((*In_AddTrain)(nil), "ticket.In_AddTrain")
	proto.RegisterType((*Out_AddTrain)(nil), "ticket.Out_AddTrain")
}

func init() { proto.RegisterFile("ticket.proto", fileDescriptor_98a6c21780e82d22) }

var fileDescriptor_98a6c21780e82d22 = []byte{
	// 687 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0x4d, 0xe2, 0x38, 0x89, 0xa7, 0x69, 0x1b, 0x36, 0x81, 0x6c, 0x53, 0x90, 0x2a, 0xf7, 0xd2,
	0x03, 0xaa, 0x50, 0x11, 0x42, 0x1c, 0xa1, 0x14, 0x14, 0xa9, 0x52, 0x25, 0xb7, 0x48, 0x1c, 0x90,
	0x2c, 0xc7, 0xde, 0x56, 0x86, 0xc6, 0x9b, 0xae, 0x37, 0x58, 0xf1, 0x9f, 0xe0, 0x87, 0xf4, 0xc8,
	0x1f, 0x44, 0x33, 0xeb, 0x14, 0xc7, 0xfd, 0xa0, 0x07, 0x4e, 0xdd, 0xf7, 0xde, 0xcc, 0x78, 0x3e,
	0x9e, 0x1a, 0xe8, 0xea, 0x38, 0xfc, 0x21, 0xf4, 0xfe, 0x4c, 0x49, 0x2d, 0x59, 0xcb, 0x20, 0xf7,
	0x0d, 0xd8, 0x47, 0x4a, 0x49, 0xc5, 0x18, 0x34, 0x43, 0x19, 0x09, 0x5e, 0xdf, 0xa9, 0xef, 0xd9,
	0x1e, 0xbd, 0x19, 0x87, 0xf6, 0x54, 0xa4, 0x69, 0x70, 0x21, 0x78, 0x63, 0xa7, 0xbe, 0xe7, 0x78,
	0x4b, 0xe8, 0xfe, 0x6e, 0x82, 0x7d, 0xa6, 0x82, 0x38, 0x61, 0x2f, 0x00, 0x52, 0x11, 0x2a, 0xa1,
	0xfd, 0x54, 0x2b, 0xca, 0x76, 0x3c, 0xc7, 0x30, 0xa7, 0x5a, 0xa1, 0xac, 0x31, 0xce, 0xa7, 0xe2,
	0xa6, 0x8a, 0x43, 0xcc, 0x21, 0x7e, 0xa1, 0x07, 0x56, 0x32, 0x9f, 0x72, 0x8b, 0x78, 0x7c, 0x62,
	0x1f, 0xe7, 0x4a, 0x4e, 0x79, 0x93, 0x28, 0x7a, 0xb3, 0x0d, 0x68, 0x68, 0xc9, 0x6d, 0x62, 0x1a,
	0x5a, 0xb2, 0x6d, 0x70, 0xce, 0xe3, 0x24, 0xf2, 0x29, 0xb0, 0x45, 0x74, 0x07, 0x89, 0x4f, 0x18,
	0x3c, 0x84, 0x36, 0x89, 0x5a, 0xf2, 0x36, 0x49, 0x2d, 0x84, 0x67, 0x92, 0x3a, 0xd5, 0x81, 0xd2,
	0xbe, 0x8e, 0xa7, 0x82, 0x77, 0x8a, 0x4e, 0x91, 0x39, 0x8b, 0xa7, 0x82, 0x6d, 0x41, 0x47, 0x60,
	0x1a, 0x8a, 0x8e, 0x99, 0x56, 0x24, 0x11, 0x49, 0xdb, 0xe0, 0x84, 0x32, 0x2d, 0x12, 0xc1, 0x7c,
	0x0f, 0x09, 0x12, 0x87, 0xd0, 0x0e, 0x83, 0xc4, 0x9f, 0xcc, 0x17, 0x7c, 0xcd, 0x7c, 0x2f, 0x0c,
	0x92, 0x0f, 0xf3, 0xc5, 0xdf, 0xd1, 0xa3, 0x40, 0x0b, 0xde, 0x2d, 0x8d, 0xfe, 0x31, 0xd0, 0x82,
	0x0d, 0xc0, 0x4e, 0x33, 0x1d, 0xe5, 0x7c, 0x9d, 0x14, 0x03, 0x70, 0x21, 0x8b, 0x28, 0xe7, 0x1b,
	0x66, 0x21, 0x0b, 0xc3, 0x88, 0x28, 0xe7, 0x9b, 0x86, 0x11, 0x51, 0x8e, 0x2b, 0xba, 0xf8, 0xae,
	0x32, 0xde, 0x33, 0x2b, 0xc2, 0x37, 0xae, 0x48, 0x65, 0xfc, 0x89, 0x59, 0x91, 0xc1, 0x51, 0xc6,
	0x99, 0xc1, 0x11, 0xe1, 0x45, 0xc6, 0xfb, 0x06, 0x2f, 0x4c, 0x7c, 0xce, 0x07, 0x45, 0x7c, 0x4e,
	0x7a, 0xce, 0x9f, 0x16, 0x3a, 0xe1, 0x2c, 0xe7, 0xcf, 0x0c, 0xce, 0x08, 0x5f, 0x69, 0x3e, 0x34,
	0xf8, 0x4a, 0x23, 0x9e, 0xe4, 0x9c, 0x1b, 0x3c, 0xc9, 0xd9, 0x2e, 0xac, 0xcf, 0xe6, 0x6a, 0x26,
	0x53, 0x41, 0x97, 0x4e, 0xf9, 0x16, 0x49, 0xdd, 0x82, 0xc4, 0x63, 0xa7, 0xee, 0x2b, 0xd8, 0x1c,
	0x27, 0xfe, 0x67, 0xa1, 0xc9, 0x3a, 0xe3, 0xe4, 0x5c, 0xfe, 0xc3, 0x3e, 0xee, 0x37, 0xe8, 0x9d,
	0xcc, 0xf5, 0x6a, 0xca, 0x2e, 0xd8, 0x02, 0x2d, 0x4b, 0xd1, 0x6b, 0x07, 0xeb, 0xfb, 0x85, 0xb1,
	0xc9, 0xc7, 0x9e, 0xd1, 0x30, 0x88, 0x56, 0x4d, 0x96, 0x2b, 0x05, 0x51, 0x19, 0xcf, 0x68, 0xee,
	0xaf, 0x3a, 0xf4, 0x2b, 0x0d, 0x1d, 0xc7, 0xa9, 0x5e, 0xf5, 0x57, 0xfd, 0x7e, 0x7f, 0x35, 0xaa,
	0xfe, 0x2a, 0xdd, 0xdb, 0xaa, 0xde, 0xfb, 0xd6, 0x86, 0x9a, 0x77, 0x6c, 0xe8, 0xba, 0x0e, 0x83,
	0xea, 0xc0, 0xd4, 0xd2, 0xa3, 0x86, 0x1e, 0x80, 0x7d, 0x19, 0x4f, 0x63, 0x4d, 0x8d, 0x59, 0x9e,
	0x01, 0xc8, 0xce, 0x82, 0x0b, 0x91, 0x52, 0x4b, 0x96, 0x67, 0x00, 0xb2, 0x5a, 0xea, 0xe0, 0x92,
	0xda, 0xb0, 0x3c, 0x03, 0xd8, 0xcb, 0xe5, 0x0c, 0x97, 0x71, 0xaa, 0xb9, 0xbd, 0x63, 0xdd, 0xde,
	0x9d, 0x19, 0x09, 0x9b, 0x72, 0xdf, 0x01, 0x1b, 0x27, 0xfe, 0x97, 0x19, 0x0e, 0xbc, 0x72, 0x1f,
	0x02, 0xd5, 0x56, 0x8b, 0xd5, 0xd3, 0x1f, 0xd7, 0x87, 0x3e, 0xce, 0x79, 0x47, 0xee, 0xd1, 0x03,
	0x63, 0x1e, 0x3d, 0xfe, 0xb6, 0x07, 0xb0, 0x36, 0x4e, 0xfc, 0xf7, 0x51, 0x64, 0xfe, 0x4d, 0xdd,
	0xe4, 0xd4, 0x1f, 0xc8, 0xf9, 0x0a, 0x5d, 0x6c, 0xaa, 0x9c, 0xf4, 0x7f, 0xba, 0x39, 0xb8, 0x6e,
	0x40, 0x97, 0x88, 0x53, 0xa1, 0x7e, 0xc6, 0xa1, 0x60, 0x87, 0xd0, 0x5d, 0x31, 0xf5, 0x70, 0x99,
	0x56, 0xf1, 0xe3, 0x88, 0x2f, 0x85, 0xaa, 0x2d, 0xdc, 0x1a, 0x3b, 0x81, 0xde, 0x6d, 0xef, 0xde,
	0x53, 0x08, 0xc5, 0xd1, 0xf3, 0xfb, 0x8a, 0xd1, 0x39, 0x6b, 0xec, 0x18, 0x36, 0xab, 0x17, 0x19,
	0x95, 0xea, 0x55, 0xb4, 0xd1, 0x76, 0xb9, 0x5c, 0x45, 0x74, 0x6b, 0xec, 0x2d, 0x74, 0x6e, 0x56,
	0xd9, 0x2f, 0x95, 0x59, 0x92, 0xa3, 0x41, 0x39, 0x7f, 0xc9, 0xba, 0xb5, 0x49, 0x8b, 0x7e, 0xa3,
	0x5e, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0x87, 0x48, 0x4e, 0xc4, 0xb3, 0x06, 0x00, 0x00,
}
