// Code generated by protoc-gen-go. DO NOT EDIT.
// source: task.proto

package task

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Task struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	UserId               string   `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	SeatTypes            string   `protobuf:"bytes,3,opt,name=seat_types,json=seatTypes,proto3" json:"seat_types,omitempty"`
	TrainDates           string   `protobuf:"bytes,4,opt,name=train_dates,json=trainDates,proto3" json:"train_dates,omitempty"`
	FindFrom             string   `protobuf:"bytes,5,opt,name=find_from,json=findFrom,proto3" json:"find_from,omitempty"`
	FindTo               string   `protobuf:"bytes,6,opt,name=find_to,json=findTo,proto3" json:"find_to,omitempty"`
	OkNo                 string   `protobuf:"bytes,10,opt,name=ok_no,json=okNo,proto3" json:"ok_no,omitempty"`
	Status               int64    `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`
	CreatedTime          int64    `protobuf:"varint,12,opt,name=created_time,json=createdTime,proto3" json:"created_time,omitempty"`
	UpdateTime           int64    `protobuf:"varint,13,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	Type                 string   `protobuf:"bytes,14,opt,name=type,proto3" json:"type,omitempty"`
	Trips                string   `protobuf:"bytes,15,opt,name=trips,proto3" json:"trips,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Task) Reset()         { *m = Task{} }
func (m *Task) String() string { return proto.CompactTextString(m) }
func (*Task) ProtoMessage()    {}
func (*Task) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{0}
}

func (m *Task) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Task.Unmarshal(m, b)
}
func (m *Task) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Task.Marshal(b, m, deterministic)
}
func (m *Task) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Task.Merge(m, src)
}
func (m *Task) XXX_Size() int {
	return xxx_messageInfo_Task.Size(m)
}
func (m *Task) XXX_DiscardUnknown() {
	xxx_messageInfo_Task.DiscardUnknown(m)
}

var xxx_messageInfo_Task proto.InternalMessageInfo

func (m *Task) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *Task) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *Task) GetSeatTypes() string {
	if m != nil {
		return m.SeatTypes
	}
	return ""
}

func (m *Task) GetTrainDates() string {
	if m != nil {
		return m.TrainDates
	}
	return ""
}

func (m *Task) GetFindFrom() string {
	if m != nil {
		return m.FindFrom
	}
	return ""
}

func (m *Task) GetFindTo() string {
	if m != nil {
		return m.FindTo
	}
	return ""
}

func (m *Task) GetOkNo() string {
	if m != nil {
		return m.OkNo
	}
	return ""
}

func (m *Task) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Task) GetCreatedTime() int64 {
	if m != nil {
		return m.CreatedTime
	}
	return 0
}

func (m *Task) GetUpdateTime() int64 {
	if m != nil {
		return m.UpdateTime
	}
	return 0
}

func (m *Task) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Task) GetTrips() string {
	if m != nil {
		return m.Trips
	}
	return ""
}

type TaskPassenger struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TaskId               string   `protobuf:"bytes,2,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	IdNum                string   `protobuf:"bytes,4,opt,name=id_num,json=idNum,proto3" json:"id_num,omitempty"`
	TelNum               string   `protobuf:"bytes,5,opt,name=tel_num,json=telNum,proto3" json:"tel_num,omitempty"`
	Type                 string   `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	SeatNum              string   `protobuf:"bytes,7,opt,name=seat_num,json=seatNum,proto3" json:"seat_num,omitempty"`
	AllEncStr            string   `protobuf:"bytes,8,opt,name=allEncStr,proto3" json:"allEncStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TaskPassenger) Reset()         { *m = TaskPassenger{} }
func (m *TaskPassenger) String() string { return proto.CompactTextString(m) }
func (*TaskPassenger) ProtoMessage()    {}
func (*TaskPassenger) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{1}
}

func (m *TaskPassenger) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskPassenger.Unmarshal(m, b)
}
func (m *TaskPassenger) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskPassenger.Marshal(b, m, deterministic)
}
func (m *TaskPassenger) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskPassenger.Merge(m, src)
}
func (m *TaskPassenger) XXX_Size() int {
	return xxx_messageInfo_TaskPassenger.Size(m)
}
func (m *TaskPassenger) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskPassenger.DiscardUnknown(m)
}

var xxx_messageInfo_TaskPassenger proto.InternalMessageInfo

func (m *TaskPassenger) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *TaskPassenger) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *TaskPassenger) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TaskPassenger) GetIdNum() string {
	if m != nil {
		return m.IdNum
	}
	return ""
}

func (m *TaskPassenger) GetTelNum() string {
	if m != nil {
		return m.TelNum
	}
	return ""
}

func (m *TaskPassenger) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TaskPassenger) GetSeatNum() string {
	if m != nil {
		return m.SeatNum
	}
	return ""
}

func (m *TaskPassenger) GetAllEncStr() string {
	if m != nil {
		return m.AllEncStr
	}
	return ""
}

type TaskDetails struct {
	Task                 *Task            `protobuf:"bytes,2,opt,name=task,proto3" json:"task,omitempty"`
	TaskPassenger        []*TaskPassenger `protobuf:"bytes,3,rep,name=task_passenger,json=taskPassenger,proto3" json:"task_passenger,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *TaskDetails) Reset()         { *m = TaskDetails{} }
func (m *TaskDetails) String() string { return proto.CompactTextString(m) }
func (*TaskDetails) ProtoMessage()    {}
func (*TaskDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{2}
}

func (m *TaskDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TaskDetails.Unmarshal(m, b)
}
func (m *TaskDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TaskDetails.Marshal(b, m, deterministic)
}
func (m *TaskDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TaskDetails.Merge(m, src)
}
func (m *TaskDetails) XXX_Size() int {
	return xxx_messageInfo_TaskDetails.Size(m)
}
func (m *TaskDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_TaskDetails.DiscardUnknown(m)
}

var xxx_messageInfo_TaskDetails proto.InternalMessageInfo

func (m *TaskDetails) GetTask() *Task {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *TaskDetails) GetTaskPassenger() []*TaskPassenger {
	if m != nil {
		return m.TaskPassenger
	}
	return nil
}

type Error struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{3}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type In_GetTaskInfo struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetTaskInfo) Reset()         { *m = In_GetTaskInfo{} }
func (m *In_GetTaskInfo) String() string { return proto.CompactTextString(m) }
func (*In_GetTaskInfo) ProtoMessage()    {}
func (*In_GetTaskInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{4}
}

func (m *In_GetTaskInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetTaskInfo.Unmarshal(m, b)
}
func (m *In_GetTaskInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetTaskInfo.Marshal(b, m, deterministic)
}
func (m *In_GetTaskInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetTaskInfo.Merge(m, src)
}
func (m *In_GetTaskInfo) XXX_Size() int {
	return xxx_messageInfo_In_GetTaskInfo.Size(m)
}
func (m *In_GetTaskInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetTaskInfo.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetTaskInfo proto.InternalMessageInfo

func (m *In_GetTaskInfo) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

type Out_GetTaskInfo struct {
	Error                *Error       `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	TaskDetails          *TaskDetails `protobuf:"bytes,2,opt,name=taskDetails,proto3" json:"taskDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Out_GetTaskInfo) Reset()         { *m = Out_GetTaskInfo{} }
func (m *Out_GetTaskInfo) String() string { return proto.CompactTextString(m) }
func (*Out_GetTaskInfo) ProtoMessage()    {}
func (*Out_GetTaskInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{5}
}

func (m *Out_GetTaskInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetTaskInfo.Unmarshal(m, b)
}
func (m *Out_GetTaskInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetTaskInfo.Marshal(b, m, deterministic)
}
func (m *Out_GetTaskInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetTaskInfo.Merge(m, src)
}
func (m *Out_GetTaskInfo) XXX_Size() int {
	return xxx_messageInfo_Out_GetTaskInfo.Size(m)
}
func (m *Out_GetTaskInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetTaskInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetTaskInfo proto.InternalMessageInfo

func (m *Out_GetTaskInfo) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetTaskInfo) GetTaskDetails() *TaskDetails {
	if m != nil {
		return m.TaskDetails
	}
	return nil
}

type In_GetTaskInfoList struct {
	Limit                int64    `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64    `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	SearchKey            string   `protobuf:"bytes,3,opt,name=search_key,json=searchKey,proto3" json:"search_key,omitempty"`
	Status               string   `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartTime            string   `protobuf:"bytes,5,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime              string   `protobuf:"bytes,6,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetTaskInfoList) Reset()         { *m = In_GetTaskInfoList{} }
func (m *In_GetTaskInfoList) String() string { return proto.CompactTextString(m) }
func (*In_GetTaskInfoList) ProtoMessage()    {}
func (*In_GetTaskInfoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{6}
}

func (m *In_GetTaskInfoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetTaskInfoList.Unmarshal(m, b)
}
func (m *In_GetTaskInfoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetTaskInfoList.Marshal(b, m, deterministic)
}
func (m *In_GetTaskInfoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetTaskInfoList.Merge(m, src)
}
func (m *In_GetTaskInfoList) XXX_Size() int {
	return xxx_messageInfo_In_GetTaskInfoList.Size(m)
}
func (m *In_GetTaskInfoList) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetTaskInfoList.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetTaskInfoList proto.InternalMessageInfo

func (m *In_GetTaskInfoList) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *In_GetTaskInfoList) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *In_GetTaskInfoList) GetSearchKey() string {
	if m != nil {
		return m.SearchKey
	}
	return ""
}

func (m *In_GetTaskInfoList) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *In_GetTaskInfoList) GetStartTime() string {
	if m != nil {
		return m.StartTime
	}
	return ""
}

func (m *In_GetTaskInfoList) GetEndTime() string {
	if m != nil {
		return m.EndTime
	}
	return ""
}

type Out_GetTaskInfoList struct {
	Error                *Error         `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	Limit                int64          `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Pages                int64          `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Total                int64          `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	TaskDetailsList      []*TaskDetails `protobuf:"bytes,5,rep,name=task_details_list,json=taskDetailsList,proto3" json:"task_details_list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Out_GetTaskInfoList) Reset()         { *m = Out_GetTaskInfoList{} }
func (m *Out_GetTaskInfoList) String() string { return proto.CompactTextString(m) }
func (*Out_GetTaskInfoList) ProtoMessage()    {}
func (*Out_GetTaskInfoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{7}
}

func (m *Out_GetTaskInfoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_GetTaskInfoList.Unmarshal(m, b)
}
func (m *Out_GetTaskInfoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_GetTaskInfoList.Marshal(b, m, deterministic)
}
func (m *Out_GetTaskInfoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_GetTaskInfoList.Merge(m, src)
}
func (m *Out_GetTaskInfoList) XXX_Size() int {
	return xxx_messageInfo_Out_GetTaskInfoList.Size(m)
}
func (m *Out_GetTaskInfoList) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_GetTaskInfoList.DiscardUnknown(m)
}

var xxx_messageInfo_Out_GetTaskInfoList proto.InternalMessageInfo

func (m *Out_GetTaskInfoList) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_GetTaskInfoList) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Out_GetTaskInfoList) GetPages() int64 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *Out_GetTaskInfoList) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Out_GetTaskInfoList) GetTaskDetailsList() []*TaskDetails {
	if m != nil {
		return m.TaskDetailsList
	}
	return nil
}

type In_UpdateTaskInfo struct {
	TaskDetails          *TaskDetails `protobuf:"bytes,1,opt,name=taskDetails,proto3" json:"taskDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *In_UpdateTaskInfo) Reset()         { *m = In_UpdateTaskInfo{} }
func (m *In_UpdateTaskInfo) String() string { return proto.CompactTextString(m) }
func (*In_UpdateTaskInfo) ProtoMessage()    {}
func (*In_UpdateTaskInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{8}
}

func (m *In_UpdateTaskInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_UpdateTaskInfo.Unmarshal(m, b)
}
func (m *In_UpdateTaskInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_UpdateTaskInfo.Marshal(b, m, deterministic)
}
func (m *In_UpdateTaskInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_UpdateTaskInfo.Merge(m, src)
}
func (m *In_UpdateTaskInfo) XXX_Size() int {
	return xxx_messageInfo_In_UpdateTaskInfo.Size(m)
}
func (m *In_UpdateTaskInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_In_UpdateTaskInfo.DiscardUnknown(m)
}

var xxx_messageInfo_In_UpdateTaskInfo proto.InternalMessageInfo

func (m *In_UpdateTaskInfo) GetTaskDetails() *TaskDetails {
	if m != nil {
		return m.TaskDetails
	}
	return nil
}

type Out_UpdateTaskInfo struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Out_UpdateTaskInfo) Reset()         { *m = Out_UpdateTaskInfo{} }
func (m *Out_UpdateTaskInfo) String() string { return proto.CompactTextString(m) }
func (*Out_UpdateTaskInfo) ProtoMessage()    {}
func (*Out_UpdateTaskInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{9}
}

func (m *Out_UpdateTaskInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_UpdateTaskInfo.Unmarshal(m, b)
}
func (m *Out_UpdateTaskInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_UpdateTaskInfo.Marshal(b, m, deterministic)
}
func (m *Out_UpdateTaskInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_UpdateTaskInfo.Merge(m, src)
}
func (m *Out_UpdateTaskInfo) XXX_Size() int {
	return xxx_messageInfo_Out_UpdateTaskInfo.Size(m)
}
func (m *Out_UpdateTaskInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_UpdateTaskInfo.DiscardUnknown(m)
}

var xxx_messageInfo_Out_UpdateTaskInfo proto.InternalMessageInfo

func (m *Out_UpdateTaskInfo) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type In_AddTask struct {
	TaskDetails          *TaskDetails `protobuf:"bytes,1,opt,name=taskDetails,proto3" json:"taskDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *In_AddTask) Reset()         { *m = In_AddTask{} }
func (m *In_AddTask) String() string { return proto.CompactTextString(m) }
func (*In_AddTask) ProtoMessage()    {}
func (*In_AddTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{10}
}

func (m *In_AddTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_AddTask.Unmarshal(m, b)
}
func (m *In_AddTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_AddTask.Marshal(b, m, deterministic)
}
func (m *In_AddTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_AddTask.Merge(m, src)
}
func (m *In_AddTask) XXX_Size() int {
	return xxx_messageInfo_In_AddTask.Size(m)
}
func (m *In_AddTask) XXX_DiscardUnknown() {
	xxx_messageInfo_In_AddTask.DiscardUnknown(m)
}

var xxx_messageInfo_In_AddTask proto.InternalMessageInfo

func (m *In_AddTask) GetTaskDetails() *TaskDetails {
	if m != nil {
		return m.TaskDetails
	}
	return nil
}

type Out_AddTask struct {
	Error                *Error       `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	TaskDetails          *TaskDetails `protobuf:"bytes,2,opt,name=taskDetails,proto3" json:"taskDetails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Out_AddTask) Reset()         { *m = Out_AddTask{} }
func (m *Out_AddTask) String() string { return proto.CompactTextString(m) }
func (*Out_AddTask) ProtoMessage()    {}
func (*Out_AddTask) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{11}
}

func (m *Out_AddTask) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_AddTask.Unmarshal(m, b)
}
func (m *Out_AddTask) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_AddTask.Marshal(b, m, deterministic)
}
func (m *Out_AddTask) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_AddTask.Merge(m, src)
}
func (m *Out_AddTask) XXX_Size() int {
	return xxx_messageInfo_Out_AddTask.Size(m)
}
func (m *Out_AddTask) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_AddTask.DiscardUnknown(m)
}

var xxx_messageInfo_Out_AddTask proto.InternalMessageInfo

func (m *Out_AddTask) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Out_AddTask) GetTaskDetails() *TaskDetails {
	if m != nil {
		return m.TaskDetails
	}
	return nil
}

type In_GetUserTaskList struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_GetUserTaskList) Reset()         { *m = In_GetUserTaskList{} }
func (m *In_GetUserTaskList) String() string { return proto.CompactTextString(m) }
func (*In_GetUserTaskList) ProtoMessage()    {}
func (*In_GetUserTaskList) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{12}
}

func (m *In_GetUserTaskList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_GetUserTaskList.Unmarshal(m, b)
}
func (m *In_GetUserTaskList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_GetUserTaskList.Marshal(b, m, deterministic)
}
func (m *In_GetUserTaskList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_GetUserTaskList.Merge(m, src)
}
func (m *In_GetUserTaskList) XXX_Size() int {
	return xxx_messageInfo_In_GetUserTaskList.Size(m)
}
func (m *In_GetUserTaskList) XXX_DiscardUnknown() {
	xxx_messageInfo_In_GetUserTaskList.DiscardUnknown(m)
}

var xxx_messageInfo_In_GetUserTaskList proto.InternalMessageInfo

func (m *In_GetUserTaskList) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type In_UpdateTaskStatus struct {
	TaskId               string   `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Status               int64    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *In_UpdateTaskStatus) Reset()         { *m = In_UpdateTaskStatus{} }
func (m *In_UpdateTaskStatus) String() string { return proto.CompactTextString(m) }
func (*In_UpdateTaskStatus) ProtoMessage()    {}
func (*In_UpdateTaskStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{13}
}

func (m *In_UpdateTaskStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_In_UpdateTaskStatus.Unmarshal(m, b)
}
func (m *In_UpdateTaskStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_In_UpdateTaskStatus.Marshal(b, m, deterministic)
}
func (m *In_UpdateTaskStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_In_UpdateTaskStatus.Merge(m, src)
}
func (m *In_UpdateTaskStatus) XXX_Size() int {
	return xxx_messageInfo_In_UpdateTaskStatus.Size(m)
}
func (m *In_UpdateTaskStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_In_UpdateTaskStatus.DiscardUnknown(m)
}

var xxx_messageInfo_In_UpdateTaskStatus proto.InternalMessageInfo

func (m *In_UpdateTaskStatus) GetTaskId() string {
	if m != nil {
		return m.TaskId
	}
	return ""
}

func (m *In_UpdateTaskStatus) GetStatus() int64 {
	if m != nil {
		return m.Status
	}
	return 0
}

type Out_UpdateTaskStatus struct {
	Error                *Error   `protobuf:"bytes,1,opt,name=Error,proto3" json:"Error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Out_UpdateTaskStatus) Reset()         { *m = Out_UpdateTaskStatus{} }
func (m *Out_UpdateTaskStatus) String() string { return proto.CompactTextString(m) }
func (*Out_UpdateTaskStatus) ProtoMessage()    {}
func (*Out_UpdateTaskStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{14}
}

func (m *Out_UpdateTaskStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Out_UpdateTaskStatus.Unmarshal(m, b)
}
func (m *Out_UpdateTaskStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Out_UpdateTaskStatus.Marshal(b, m, deterministic)
}
func (m *Out_UpdateTaskStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Out_UpdateTaskStatus.Merge(m, src)
}
func (m *Out_UpdateTaskStatus) XXX_Size() int {
	return xxx_messageInfo_Out_UpdateTaskStatus.Size(m)
}
func (m *Out_UpdateTaskStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_Out_UpdateTaskStatus.DiscardUnknown(m)
}

var xxx_messageInfo_Out_UpdateTaskStatus proto.InternalMessageInfo

func (m *Out_UpdateTaskStatus) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type OrderMsg struct {
	SequenceNo           string   `protobuf:"bytes,1,opt,name=sequenceNo,proto3" json:"sequenceNo,omitempty"`
	PassengerIdTypeName  string   `protobuf:"bytes,2,opt,name=passengerIdTypeName,proto3" json:"passengerIdTypeName,omitempty"`
	PassengerName        string   `protobuf:"bytes,3,opt,name=passengerName,proto3" json:"passengerName,omitempty"`
	PassengerIdNo        string   `protobuf:"bytes,4,opt,name=passengerIdNo,proto3" json:"passengerIdNo,omitempty"`
	FromStationName      string   `protobuf:"bytes,5,opt,name=fromStationName,proto3" json:"fromStationName,omitempty"`
	ToStationName        string   `protobuf:"bytes,6,opt,name=toStationName,proto3" json:"toStationName,omitempty"`
	StationTrainCode     string   `protobuf:"bytes,7,opt,name=stationTrainCode,proto3" json:"stationTrainCode,omitempty"`
	StartTrainDate       string   `protobuf:"bytes,8,opt,name=startTrainDate,proto3" json:"startTrainDate,omitempty"`
	TicketPrice          string   `protobuf:"bytes,9,opt,name=ticketPrice,proto3" json:"ticketPrice,omitempty"`
	TicketTypeName       string   `protobuf:"bytes,10,opt,name=ticketTypeName,proto3" json:"ticketTypeName,omitempty"`
	CoachName            string   `protobuf:"bytes,11,opt,name=coachName,proto3" json:"coachName,omitempty"`
	SeatName             string   `protobuf:"bytes,12,opt,name=seatName,proto3" json:"seatName,omitempty"`
	SeatTypeName         string   `protobuf:"bytes,13,opt,name=seatTypeName,proto3" json:"seatTypeName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderMsg) Reset()         { *m = OrderMsg{} }
func (m *OrderMsg) String() string { return proto.CompactTextString(m) }
func (*OrderMsg) ProtoMessage()    {}
func (*OrderMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_ce5d8dd45b4a91ff, []int{15}
}

func (m *OrderMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderMsg.Unmarshal(m, b)
}
func (m *OrderMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderMsg.Marshal(b, m, deterministic)
}
func (m *OrderMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderMsg.Merge(m, src)
}
func (m *OrderMsg) XXX_Size() int {
	return xxx_messageInfo_OrderMsg.Size(m)
}
func (m *OrderMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderMsg.DiscardUnknown(m)
}

var xxx_messageInfo_OrderMsg proto.InternalMessageInfo

func (m *OrderMsg) GetSequenceNo() string {
	if m != nil {
		return m.SequenceNo
	}
	return ""
}

func (m *OrderMsg) GetPassengerIdTypeName() string {
	if m != nil {
		return m.PassengerIdTypeName
	}
	return ""
}

func (m *OrderMsg) GetPassengerName() string {
	if m != nil {
		return m.PassengerName
	}
	return ""
}

func (m *OrderMsg) GetPassengerIdNo() string {
	if m != nil {
		return m.PassengerIdNo
	}
	return ""
}

func (m *OrderMsg) GetFromStationName() string {
	if m != nil {
		return m.FromStationName
	}
	return ""
}

func (m *OrderMsg) GetToStationName() string {
	if m != nil {
		return m.ToStationName
	}
	return ""
}

func (m *OrderMsg) GetStationTrainCode() string {
	if m != nil {
		return m.StationTrainCode
	}
	return ""
}

func (m *OrderMsg) GetStartTrainDate() string {
	if m != nil {
		return m.StartTrainDate
	}
	return ""
}

func (m *OrderMsg) GetTicketPrice() string {
	if m != nil {
		return m.TicketPrice
	}
	return ""
}

func (m *OrderMsg) GetTicketTypeName() string {
	if m != nil {
		return m.TicketTypeName
	}
	return ""
}

func (m *OrderMsg) GetCoachName() string {
	if m != nil {
		return m.CoachName
	}
	return ""
}

func (m *OrderMsg) GetSeatName() string {
	if m != nil {
		return m.SeatName
	}
	return ""
}

func (m *OrderMsg) GetSeatTypeName() string {
	if m != nil {
		return m.SeatTypeName
	}
	return ""
}

func init() {
	proto.RegisterType((*Task)(nil), "task.Task")
	proto.RegisterType((*TaskPassenger)(nil), "task.Task_passenger")
	proto.RegisterType((*TaskDetails)(nil), "task.TaskDetails")
	proto.RegisterType((*Error)(nil), "task.Error")
	proto.RegisterType((*In_GetTaskInfo)(nil), "task.In_GetTaskInfo")
	proto.RegisterType((*Out_GetTaskInfo)(nil), "task.Out_GetTaskInfo")
	proto.RegisterType((*In_GetTaskInfoList)(nil), "task.In_GetTaskInfoList")
	proto.RegisterType((*Out_GetTaskInfoList)(nil), "task.Out_GetTaskInfoList")
	proto.RegisterType((*In_UpdateTaskInfo)(nil), "task.In_UpdateTaskInfo")
	proto.RegisterType((*Out_UpdateTaskInfo)(nil), "task.Out_UpdateTaskInfo")
	proto.RegisterType((*In_AddTask)(nil), "task.In_AddTask")
	proto.RegisterType((*Out_AddTask)(nil), "task.Out_AddTask")
	proto.RegisterType((*In_GetUserTaskList)(nil), "task.In_GetUserTaskList")
	proto.RegisterType((*In_UpdateTaskStatus)(nil), "task.In_UpdateTaskStatus")
	proto.RegisterType((*Out_UpdateTaskStatus)(nil), "task.Out_UpdateTaskStatus")
	proto.RegisterType((*OrderMsg)(nil), "task.OrderMsg")
}

func init() { proto.RegisterFile("task.proto", fileDescriptor_ce5d8dd45b4a91ff) }

var fileDescriptor_ce5d8dd45b4a91ff = []byte{
	// 1014 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xef, 0x6e, 0x1b, 0x45,
	0x10, 0x8f, 0x7d, 0x3e, 0xff, 0x99, 0x4b, 0xec, 0x64, 0x93, 0xd2, 0x8b, 0x81, 0x92, 0x9c, 0x10,
	0x0a, 0x48, 0x54, 0x55, 0x2a, 0x84, 0x10, 0xf0, 0xa1, 0xa2, 0x29, 0xb5, 0x0a, 0x6e, 0x75, 0x71,
	0x3f, 0x9f, 0x8e, 0xbb, 0x4d, 0x72, 0xd8, 0xbe, 0x35, 0xbb, 0x6b, 0xa4, 0x3c, 0x10, 0x0f, 0xc0,
	0x47, 0x1e, 0x01, 0x9e, 0x87, 0x07, 0x40, 0x33, 0xbb, 0x77, 0xbe, 0xbb, 0xba, 0xb4, 0xca, 0x27,
	0xdf, 0xfc, 0x7e, 0xb3, 0xb3, 0x33, 0xb3, 0xf3, 0xc7, 0x00, 0x3a, 0x56, 0xf3, 0x87, 0x2b, 0x29,
	0xb4, 0x60, 0x1d, 0xfc, 0x0e, 0xfe, 0x6e, 0x43, 0x67, 0x16, 0xab, 0x39, 0xbb, 0x0f, 0x3d, 0x04,
	0xa2, 0x2c, 0xf5, 0x5b, 0x27, 0xad, 0xb3, 0x41, 0xd8, 0x45, 0x71, 0x92, 0x22, 0xb1, 0x56, 0x5c,
	0x22, 0xd1, 0x36, 0x04, 0x8a, 0x93, 0x94, 0x7d, 0x0c, 0xa0, 0x78, 0xac, 0x23, 0x7d, 0xbb, 0xe2,
	0xca, 0x77, 0x88, 0x1b, 0x20, 0x32, 0x43, 0x80, 0x7d, 0x02, 0x9e, 0x96, 0x71, 0x96, 0x47, 0x69,
	0xac, 0xb9, 0xf2, 0x3b, 0xc4, 0x03, 0x41, 0x4f, 0x11, 0x61, 0x1f, 0xc2, 0xe0, 0x2a, 0xcb, 0xd3,
	0xe8, 0x4a, 0x8a, 0xa5, 0xef, 0x12, 0xdd, 0x47, 0xe0, 0x99, 0x14, 0x4b, 0xbc, 0x95, 0x48, 0x2d,
	0xfc, 0xae, 0xb9, 0x15, 0xc5, 0x99, 0x60, 0x87, 0xe0, 0x8a, 0x79, 0x94, 0x0b, 0x1f, 0x08, 0xee,
	0x88, 0xf9, 0x54, 0xb0, 0x0f, 0xa0, 0xab, 0x74, 0xac, 0xd7, 0xca, 0xf7, 0x4e, 0x5a, 0x67, 0x4e,
	0x68, 0x25, 0x76, 0x0a, 0xbb, 0x89, 0xe4, 0xb1, 0xe6, 0x69, 0xa4, 0xb3, 0x25, 0xf7, 0x77, 0x89,
	0xf5, 0x2c, 0x36, 0xcb, 0x96, 0x1c, 0xdd, 0x5c, 0xaf, 0xd0, 0x45, 0xa3, 0xb1, 0x47, 0x1a, 0x60,
	0x20, 0x52, 0x60, 0xd0, 0xc1, 0x08, 0xfd, 0xa1, 0xb9, 0x0f, 0xbf, 0xd9, 0x11, 0xb8, 0x5a, 0x66,
	0x2b, 0xe5, 0x8f, 0x08, 0x34, 0x42, 0xf0, 0x4f, 0x0b, 0x86, 0x98, 0xcb, 0x68, 0x15, 0x2b, 0xc5,
	0xf3, 0x6b, 0x2e, 0xd9, 0x10, 0xda, 0x65, 0x42, 0xdb, 0x59, 0x5a, 0xcd, 0x72, 0xbb, 0x96, 0x65,
	0x06, 0x9d, 0x3c, 0x5e, 0x72, 0x9b, 0x46, 0xfa, 0x66, 0xf7, 0xa0, 0x9b, 0xa5, 0x51, 0xbe, 0x5e,
	0xda, 0xe4, 0xb9, 0x59, 0x3a, 0x5d, 0x53, 0x6a, 0x34, 0x5f, 0x10, 0xee, 0x5a, 0x1b, 0x7c, 0x81,
	0x44, 0xe1, 0x69, 0xb7, 0xe2, 0xe9, 0x31, 0xf4, 0xe9, 0x91, 0x50, 0xbb, 0x47, 0x78, 0x0f, 0x65,
	0x54, 0xff, 0x08, 0x06, 0xf1, 0x62, 0x71, 0x91, 0x27, 0x97, 0x5a, 0xfa, 0x7d, 0xf3, 0x7c, 0x25,
	0x10, 0xfc, 0x0a, 0x1e, 0xc6, 0xf2, 0x94, 0xeb, 0x38, 0x5b, 0x28, 0xf6, 0x00, 0xa8, 0x5e, 0xc8,
	0x6b, 0xef, 0x1c, 0x1e, 0x52, 0x21, 0xa1, 0x42, 0x48, 0x38, 0xfb, 0x16, 0x86, 0xba, 0x16, 0xba,
	0xef, 0x9c, 0x38, 0x67, 0xde, 0xf9, 0xd1, 0x46, 0x73, 0xc3, 0x85, 0x7b, 0x08, 0xbe, 0x2a, 0xc4,
	0xe0, 0x2b, 0x70, 0x2f, 0xa4, 0x14, 0x12, 0x23, 0x48, 0x44, 0xca, 0x29, 0x61, 0x6e, 0x48, 0xdf,
	0xcc, 0x87, 0xde, 0x92, 0x2b, 0x15, 0x5f, 0x73, 0x9b, 0xb2, 0x42, 0x0c, 0x3e, 0x87, 0xe1, 0x24,
	0x8f, 0x7e, 0xe4, 0x1a, 0xad, 0x4f, 0xf2, 0x2b, 0xf1, 0xd6, 0x22, 0x0e, 0x32, 0x18, 0xbd, 0x5c,
	0xeb, 0x9a, 0xee, 0x29, 0xb8, 0x1c, 0x2f, 0x25, 0x4d, 0xef, 0xdc, 0x33, 0x8e, 0x92, 0x1f, 0xa1,
	0x61, 0xd8, 0x63, 0xf0, 0xf4, 0x26, 0x07, 0x36, 0xf6, 0x83, 0x4d, 0x44, 0x96, 0x08, 0xab, 0x5a,
	0xc1, 0x9f, 0x2d, 0x60, 0x75, 0xb7, 0x7e, 0xca, 0x94, 0xc6, 0x92, 0x59, 0x64, 0xcb, 0x4c, 0xd3,
	0x75, 0x4e, 0x68, 0x04, 0x44, 0x57, 0xf1, 0x35, 0x37, 0xb6, 0x9d, 0xd0, 0x08, 0xb6, 0xb3, 0x64,
	0x72, 0x13, 0xcd, 0xf9, 0x6d, 0xa5, 0xb3, 0x64, 0x72, 0xf3, 0x82, 0xdf, 0x56, 0xaa, 0xdd, 0xd4,
	0x45, 0x51, 0xed, 0x78, 0x4c, 0xc7, 0x52, 0x9b, 0x4a, 0x76, 0xed, 0x31, 0x44, 0xa8, 0x90, 0x8f,
	0xa1, 0xcf, 0x73, 0xdb, 0x08, 0xa6, 0x44, 0x7a, 0x3c, 0xa7, 0x26, 0x08, 0xfe, 0x6a, 0xc1, 0x61,
	0x23, 0x3f, 0xe4, 0xf4, 0x7b, 0xe4, 0xa8, 0x8c, 0xab, 0xbd, 0x35, 0x2e, 0xa7, 0x1a, 0x17, 0xb6,
	0x8d, 0xd0, 0xf1, 0x82, 0xfc, 0x76, 0x42, 0x23, 0xb0, 0xef, 0xe1, 0x80, 0x1e, 0x2d, 0x35, 0x09,
	0x8c, 0x16, 0x99, 0xd2, 0xbe, 0x4b, 0xd5, 0xb3, 0x25, 0xd7, 0xa3, 0x4a, 0xae, 0xd1, 0xc7, 0xe0,
	0x39, 0x1c, 0x4c, 0xf2, 0xe8, 0xb5, 0x69, 0xd8, 0xe2, 0x71, 0x1b, 0x2f, 0xd7, 0x7a, 0xaf, 0x97,
	0xfb, 0x1a, 0x18, 0x26, 0xa1, 0x61, 0xea, 0xd4, 0x16, 0xe7, 0xd6, 0x1c, 0xd0, 0x4f, 0xf0, 0x04,
	0x60, 0x92, 0x47, 0x4f, 0xd2, 0x94, 0x26, 0xe9, 0x9d, 0xee, 0xe6, 0xe0, 0xe1, 0xdd, 0x85, 0x8d,
	0x77, 0x5f, 0x7a, 0xb7, 0xe2, 0xfc, 0xb2, 0xa8, 0xcd, 0xd7, 0x8a, 0x4b, 0xd4, 0xa2, 0x67, 0xae,
	0x8c, 0xf8, 0x56, 0x75, 0xc4, 0x07, 0xcf, 0xe0, 0xb0, 0x96, 0xdb, 0x4b, 0x53, 0x68, 0x6f, 0xdd,
	0x15, 0x9b, 0xca, 0x6c, 0x57, 0xe7, 0x70, 0xf0, 0x0d, 0x1c, 0xd5, 0x33, 0x7b, 0x59, 0xcc, 0xe7,
	0x77, 0xe6, 0xf6, 0x5f, 0x07, 0xfa, 0x2f, 0x65, 0xca, 0xe5, 0xcf, 0xea, 0x9a, 0x3d, 0xc0, 0xc6,
	0xf8, 0x6d, 0xcd, 0xf3, 0x84, 0x4f, 0x85, 0xbd, 0xbb, 0x82, 0xb0, 0x47, 0x70, 0x58, 0x0e, 0x99,
	0x49, 0x8a, 0x7b, 0x68, 0x8a, 0x43, 0xd5, 0xcc, 0x8d, 0x6d, 0x14, 0xfb, 0x14, 0xf6, 0x4a, 0x78,
	0xba, 0x19, 0xc0, 0x75, 0xb0, 0xa6, 0x35, 0x49, 0xa7, 0xc2, 0x36, 0x5e, 0x1d, 0x64, 0x67, 0x30,
	0xc2, 0x5d, 0x86, 0xb1, 0x65, 0x22, 0x27, 0x6b, 0xa6, 0x09, 0x9b, 0x30, 0xda, 0xd3, 0xa2, 0xaa,
	0x67, 0xfa, 0xb1, 0x0e, 0xb2, 0x2f, 0x60, 0x5f, 0x19, 0x71, 0x86, 0x5b, 0xf3, 0x07, 0x9c, 0x8c,
	0x66, 0x86, 0xbf, 0x81, 0xb3, 0xcf, 0x60, 0x68, 0x3a, 0xbd, 0xd8, 0xaf, 0x76, 0xa2, 0x37, 0x50,
	0x76, 0x02, 0x9e, 0xce, 0x92, 0x39, 0xd7, 0xaf, 0x64, 0x96, 0x70, 0x7f, 0x40, 0x4a, 0x55, 0x08,
	0x2d, 0x19, 0xb1, 0x4c, 0x9f, 0xd9, 0xb4, 0x0d, 0x14, 0xd7, 0x47, 0x22, 0xe2, 0xe4, 0x86, 0x54,
	0x3c, 0x33, 0x6c, 0x4a, 0x80, 0x8d, 0xcd, 0xde, 0x21, 0x72, 0xd7, 0xec, 0xf6, 0x42, 0x66, 0x01,
	0xec, 0x16, 0x7f, 0x13, 0x88, 0xdf, 0x23, 0xbe, 0x86, 0x9d, 0xff, 0xe1, 0x98, 0xfd, 0x73, 0xc9,
	0xe5, 0xef, 0xe8, 0xd5, 0x77, 0xe0, 0x55, 0x87, 0xb7, 0x5d, 0x2b, 0xf5, 0x39, 0x3b, 0xbe, 0x67,
	0xd0, 0xc6, 0x24, 0x0b, 0x76, 0xd8, 0x73, 0x18, 0x35, 0x47, 0x9b, 0xbf, 0xcd, 0x02, 0x32, 0xe3,
	0xe3, 0xad, 0x56, 0x68, 0xd6, 0xec, 0xb0, 0x0b, 0x18, 0x36, 0xe6, 0xc3, 0xfd, 0xd2, 0x50, 0x9d,
	0x18, 0xfb, 0x1b, 0x3b, 0x75, 0x26, 0xd8, 0x61, 0x8f, 0xa0, 0x57, 0xb4, 0xfa, 0x7e, 0x79, 0xde,
	0x22, 0xe3, 0x83, 0xcd, 0x41, 0x0b, 0x95, 0x21, 0xd4, 0xda, 0xb6, 0x16, 0x42, 0x95, 0xf9, 0xff,
	0x10, 0x5e, 0xc0, 0xfe, 0x1b, 0x8d, 0x78, 0xbc, 0x25, 0x08, 0x43, 0x8d, 0xc7, 0xdb, 0xc2, 0x30,
	0x5c, 0xb0, 0xf3, 0x4b, 0x97, 0xfe, 0x4c, 0x3e, 0xfe, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xa8, 0xff,
	0xce, 0x8d, 0x5a, 0x0a, 0x00, 0x00,
}
