version: '3.6'

services:
  consul1: 
    image: consul:latest
    container_name: consul1
    restart: always
    network_mode: mynet
    command: agent -server -client=0.0.0.0 -bootstrap-expect=3 -node=consul1 -datacenter=dc1
  consul2:
    image: consul:latest
    container_name: consul2
    network_mode: mynet
    restart: always
    command: agent -server -client=0.0.0.0 -retry-join=consul1 -node=consul2 -datacenter=dc1
  consul3:
    image: consul:latest
    container_name: consul3
    network_mode: mynet
    restart: always
    ports:
      - 8500:8500
    command: agent -client=0.0.0.0 -retry-join=consul1 -ui -node=client1 -datacenter=dc1